# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 11:17
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


def create_achievement_reward_for_coins(apps, schema_editor):
    Achievement = apps.get_model('achievement', 'Achievement')
    Reward = apps.get_model('achievement', 'Reward')

    achievement = Achievement.objects.create(
        code=settings.ACHIEVEMENT_CH_CODE_FILL_PROFILE,
        name='Fill profile',
    )
    reward = Reward.objects.create(
        code=settings.ACHIEVEMENT_REWARD_CH_CODE_COIN,
        name='Receiving coins',
        extra_data={'link': '', 'coins': 0},
    )
    achievement.rewards.add(reward)


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_userreward_extra_data'),
    ]

    operations = [
        migrations.RunPython(create_achievement_reward_for_coins),
    ]
