# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'user', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='consultant', to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('languages', models.ManyToManyField(blank=True, to='core.Language')),
                ('primary_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primary Phone'),),
                ('secondary_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number 2')),
                (
                    'status', models.CharField(
                        choices=[
                            ('A', 'Active'), ('D', 'Disabled'), ('P', 'Pending validation'),
                        ], default='P', max_length=1, verbose_name='Consultant status',
                    ),
                ),
                (
                    'web_status', models.CharField(
                        choices=[
                            ('A', 'Active'), ('D', 'Disabled'), ('P', 'Pending'),
                        ], default='P', max_length=1, verbose_name='Consultant Public web status',
                    ),
                ),
                (
                    'public_sites', multiselectfield.db.fields.MultiSelectField(
                        blank=True, choices=[('S', 'Speakers Site'), ('W', 'ExO Works Site')], max_length=3, null=True)
                ),
            ],
            options={
                'verbose_name_plural': 'Consultants',
                'verbose_name': 'Consultant',
                'ordering': ['user__short_name'],
                'permissions': (('consultant_list', 'List&Export consultants'), ('consultant_edit_profile', 'Edit consultants'), ('skill_assessment_edit', 'Edit Skill Assessment'), ('consultant_view_full_profile', 'View Full Profile'), ('registration_process_edit', 'Edit Registration Process')), 'verbose_name': 'Consultant', 'verbose_name_plural': 'Consultants',
            },
        ),
        migrations.CreateModel(
            name='ConsultantExOProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('personal_mtp', models.TextField(blank=True, null=True)),
                (
                    'mtp_mastery', models.IntegerField(
                        blank=True, choices=[
                            (0, "I haven't read about it"), (1, 'I have read about it and understand it'), (2, 'I have studied it in some detail'), (
                                3, 'I have implemented this once or twice',
                            ), (4, 'I have implemented this several times'), (5, "I’m considered a thought leader in this domain,        and I've published articles/papers about it"),
                        ], null=True,
                    ),
                ),
                (
                    'areas_expertise', multiselectfield.db.fields.MultiSelectField(
                        blank=True, choices=[
                            (1, 'Accelerating technologies'), (2, 'Advising organizations for changes'), (3, 'Advising technologies'), (4, 'Advising Startups'), (
                                5, 'Advising incremental innovation',
                            ), (6, 'Evaluation innovation projects'), (7, 'Planning innovation projects'), (8, 'Managing OKR systems'), (9, 'Executing incremental innovation'), (10, 'Executing disruptive innovation'),
                        ], max_length=20, null=True,
                    ),
                ),
                (
                    'wanted_roles', multiselectfield.db.fields.MultiSelectField(
                        blank=True, choices=[
                            (1, 'ExO Collaborator'), (2, 'ExO Coach'), (3, 'ExO Consultant'), (4, 'ExO Speaker'),
                        ], max_length=7, null=True,
                    ),
                ),
                (
                    'experience_consulting', models.IntegerField(
                        blank=True, choices=[
                            (1, 'Informal advisory'), (2, 'Informal consulting'), (
                                3, '1-2 years formal consulting',
                            ), (4, '3-5 years formal consulting'), (5, '+5 years formal consulting'),
                        ], null=True,
                    ),
                ),
                (
                    'consultant', models.OneToOneField(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, related_name='exo_profile', to='consultant.Consultant',
                    ),
                ),
                (
                    'availability', models.CharField(
                        blank=True, choices=[
                            ('F', 'Fulltime'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'),
                        ], max_length=1, null=True,
                    ),
                ),
                ('availability_hours', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
