# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


def create_consultant_validation(apps, schema_editor):
    ConsultantValidation = apps.get_model('consultant', 'ConsultantValidation')
    for key, _ in settings.CONSULTANT_VALIDATION_CH_TYPE:
        validation, created = ConsultantValidation.objects.get_or_create(
            name=key,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
        ('relation', '0001_squashed_0040_consultantactivity'),
        ('exo_area', '0002_auto_20171130_1807'),
        ('industry', '0001_squashed_0004_auto_20171016_1113'),
        ('keywords', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '__first__'),
        ('exo_attributes', '0002_auto_20170703_0655'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exo_activity', '0001_squashed_0007_auto_20171215_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'name', models.CharField(
                        choices=[
                            ('G', 'Agreement'), ('S', 'Skill Assessment'),
                            ('A', 'Application'), ('T', 'Test'), ('U', 'User'), ('F', 'On boarding'),
                        ], max_length=1,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Consultants Validations',
                'verbose_name': 'Consultant Validation',
            },
        ),
        migrations.CreateModel(
            name='ConsultantValidationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'user_from', models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='consultants_validations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'status', models.CharField(
                        choices=[
                            ('W', 'Waiting to send'), ('S', 'Sent'), ('K', 'Notification skipped'), (
                                'P', 'Pending',
                            ), ('A', 'Accepted'), ('D', 'Denied'),
                        ], default='W', max_length=1,
                    ),
                ),
                (
                    'consultant', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='validations', to='consultant.Consultant',
                    ),
                ),
                (
                    'validation', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='validations', to='consultant.ConsultantValidation',
                    ),
                ),
                ('_description', models.TextField(blank=True, null=True)),
                (
                    'content_type', models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType',
                    ),
                ),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCoreArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='interests',
            field=models.ManyToManyField(to='consultant.Interest', verbose_name='Interests'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='skills',
            field=models.ManyToManyField(to='consultant.SkillCoreArea', verbose_name='Skills & Core Knowledge Areas'),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'network_type', models.CharField(
                        choices=[
                            ('S', 'Skype'), ('L', 'Linkedin'), ('T', 'Twitter'), (
                                'M',
                                'Medium',
                            ), ('P', 'Website'), ('F', 'Facebook'),
                        ], max_length=1,
                    ),
                ),
                ('value', models.CharField(max_length=255)),
                (
                    'user', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='social_networks', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=create_consultant_validation,
        ),
        migrations.AlterUniqueTogether(
            name='consultantvalidationstatus',
            unique_together={('validation', 'consultant')},
        ),
        migrations.AddField(
            model_name='consultant',
            name='_industries',
            field=models.ManyToManyField(
                related_name='_consultants',
                through='relation.ConsultantIndustry', to='industry.Industry',
            ),
        ),
        migrations.AddField(
            model_name='consultant',
            name='_exo_attributes',
            field=models.ManyToManyField(
                related_name='_consultants',
                through='relation.ConsultantExOAttribute', to='exo_attributes.ExOAttribute',
            ),
        ),
        migrations.AddField(
            model_name='consultant',
            name='_keywords',
            field=models.ManyToManyField(
                related_name='_consultants',
                through='relation.ConsultantKeyword', to='keywords.Keyword',
            ),
        ),
        migrations.CreateModel(
            name='ContractingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                (
                    'profile', models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='contracting_data', to='consultant.ConsultantExOProfile',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='_exo_areas',
            field=models.ManyToManyField(
                related_name='_consultants',
                through='relation.ConsultantExOArea', to='exo_area.ExOArea',
            ),
        ),
        migrations.CreateModel(
            name='BulkCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('file_csv', models.FileField(null=True, upload_to='bulk_creation_consultant', verbose_name='Upload the csv file')),
                (
                    'created_by', models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='consultant_bulkcreation_related', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='BulkCreationConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('error_message', models.CharField(max_length=100)),
                (
                    'bulk_creation', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='consultants', to='consultant.BulkCreation',
                    ),
                ),
                (
                    'consultant', models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, to='consultant.Consultant',
                    ),
                ),
                ('coins', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='Success', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consultantexoprofile',
            name='_exo_activities',
            field=models.ManyToManyField(
                related_name='consultant_profiles',
                through='relation.ConsultantActivity', to='exo_activity.ExOActivity',
            ),
        ),
        migrations.AddField(
            model_name='bulkcreation',
            name='_consultants',
            field=models.ManyToManyField(
                blank=True, related_name='bulks',
                through='consultant.BulkCreationConsultant', to='consultant.Consultant',
            ),
        ),
    ]
