# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0002_squashed_0057_merge_20171220_1152'),
    ]

    operations = [
    ]
