# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0058_merge_20180212_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='user',
        ),
        migrations.AlterField(
            model_name='consultantexoprofile',
            name='mtp_mastery',
            field=models.IntegerField(blank=True, choices=[(0, 'I haven’t read about it'), (1, 'I have read about it and understand it'), (2, 'I have studied it in some detail'), (3, 'I have implemented this once or twice'), (4, 'I have implemented this several times'), (5, 'I’m considered a thought leader in this domain, and I’ve published articles/papers about it')], null=True),
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
