# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-19 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0009_auto_20181219_1719'),
        ('consultant', '0060_consultantexoprofile_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='SkillCoreArea',
        ),
    ]
