# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-19 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0061_auto_20181219_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'ordering': ['user__short_name'], 'permissions': (('consultant_list', 'List&Export consultants'), ('consultant_edit_profile', 'Edit consultants'), (
                'consultant_view_full_profile', 'View Full Profile'), ('registration_process_edit', 'Edit Registration Process')), 'verbose_name': 'Consultant', 'verbose_name_plural': 'Consultants'},
        ),
        migrations.RemoveField(
            model_name='consultantexoprofile',
            name='areas_expertise',
        ),
        migrations.RemoveField(
            model_name='consultantexoprofile',
            name='experience_consulting',
        ),
        migrations.RemoveField(
            model_name='consultantexoprofile',
            name='wanted_roles',
        ),
    ]
