# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-14 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0062_auto_20181219_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractingdata',
            name='tax_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
