# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-16 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0063_contractingdata_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantvalidationstatus',
            name='user_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultants_validations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
