# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-16 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0064_auto_20190716_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantvalidationstatus',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultants_validations', to=settings.AUTH_USER_MODEL),
        ),
    ]
