# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-31 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0065_auto_20190716_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractingdata',
            name='tax_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
