# Generated by Django 2.2.5 on 2019-09-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0066_auto_20190731_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'ordering': ['user__short_name'], 'permissions': (('consultant_list', 'List&Export consultants'), ('consultant_edit_profile', 'Edit consultants'), (
                'consultant_view_full_profile', 'View Full Profile'), ('registration_process_edit', 'Edit Registration Process')), 'verbose_name': 'Consultant', 'verbose_name_plural': 'Consultants'},
        ),
    ]
