# Generated by Django 2.2.6 on 2019-10-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo_role', '0001_initial'),
        ('relation', '0013_auto_20191023_1613'),
        ('consultant', '0067_auto_20190904_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='certification_roles',
            field=models.ManyToManyField(
                blank=True, related_name='certification_roles',
                through='relation.ConsultantRole',
                to='exo_role.CertificationRole'),
        ),
    ]
