# Generated by Django 2.2.6 on 2019-11-08 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


def create_members(apps, schema_editor):
    QASession = apps.get_model('qa_session', 'qasession')
    QASessionAdvisor = apps.get_model('qa_session', 'QASessionAdvisor')

    for qa_session in QASession.objects.all():
        for advisor in qa_session.advisors.all():
            QASessionAdvisor.objects.get_or_create(
                consultant_project_role=advisor,
                qa_session=qa_session,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0015_auto_20191031_1517'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_session', '0002_qasession_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qasession',
            name='advisors',
            field=models.ManyToManyField(related_name='qa_sessions_advisors', to='relation.ConsultantProjectRole'),
        ),
        migrations.AlterField(
            model_name='qasession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='QASessionAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('consultant_project_role', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='qa_session_advisors', to='relation.ConsultantProjectRole')),
                ('created_by', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='qa_session_qasessionadvisor_related', to=settings.AUTH_USER_MODEL)),
                ('qa_session', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='qa_session_advisors', to='qa_session.QASession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='qasession',
            name='members',
            field=models.ManyToManyField(
                related_name='qa_sessions',
                through='qa_session.QASessionAdvisor',
                to='relation.ConsultantProjectRole',
            ),
        ),
        migrations.RunPython(create_members),
    ]
