# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_squashed_0011_auto_20190409_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_type',
            field=models.CharField(choices=[('C', 'Circle'), ('Q', 'Q-A Session'), ('P', 'Project'), ('A', 'Announcement')], max_length=1),
        ),
    ]
