# Generated by Django 2.2.5 on 2019-09-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20190703_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'base_manager_name': 'objects', 'ordering': [
                '-modified'], 'permissions': (('edit_post', 'Edit Post'),), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
