# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 09:56
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.management import call_command

import django.utils.timezone
import model_utils.fields


def load_languages(apps, schema_editor):
    call_command('update_core_languages')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Language Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=load_languages,
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
