# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0001_initial'),
        ('relation', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='users',
            field=models.ManyToManyField(
                related_name='partners',
                through='relation.PartnerUserRole', to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
