# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone

import model_utils.fields
import utils.images.fields
import utils.models.slug_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(default='', max_length=100)),
                (
                    'profile_picture', utils.images.fields.PowerImageField(
                        blank=True, choice_field='selectable_profile_picture',
                        null=True, thumbnails=((56, 56), (150, 150)), upload_to='avatars', verbose_name='profile picture',
                    ),
                ),
                (
                    'selectable_profile_picture', models.CharField(
                        blank=True, choices=[
                            ('theme/gallery/1.jpg', 'Image1.jpg'),
                        ], default='theme/gallery/1.jpg', help_text='An image fallback when no profile picture uploaded', max_length=255, verbose_name='selected profile picture',
                    ),
                ),
                (
                    'slug', utils.models.slug_field.TagAutoSlugField(
                        always_update=True,
                        editable=False, null=True, populate_from='name', unique=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'permissions': (('partner_edit', 'Edit Partner information'), ('partner_add_user', 'Add user role'), ('partner_delete_user', 'Delete user role'), ('partner_remove', 'Remove Partner'), ('partner_view', 'View General Partner information'), ('list_partner', 'List partner')),
            },
        ),
    ]
