# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-18 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import utils.mixins.location_timezone_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_squashed_0010_auto_20170523_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='timezone',
            field=utils.mixins.location_timezone_mixin.TimeZoneField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
