# Generated by Django 2.2.4 on 2019-08-26 14:48

from django.db import migrations
import utils.images.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20190613_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='profile_picture',
            field=utils.images.fields.PowerImageField(blank=True, choice_field='selectable_profile_picture', null=True, thumbnails=(
                (24, 24), (48, 48), (96, 96), (144, 144)), upload_to='avatars', verbose_name='profile picture'),
        ),
    ]
