# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 07:22
from __future__ import unicode_literals

from django.db import migrations


def create_initial_group(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
        ('exo_accounts', '0001_squashed_0013_auto_20190524_0613')
    ]

    operations = []
