# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=150, verbose_name='ExoProject name')),
            ],
            options={
                'permissions': (('edit_exoproject', 'Edit ExoProject'), ('view_exoproject', 'View ExoProject'), ('list_exoproject', 'List ExoProject')),
                'verbose_name': 'ExoProject',
                'verbose_name_plural': 'ExoProjects',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                (
                    'project_ptr', models.OneToOneField(
                        auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True, primary_key=True, serialize=False, to='project.Project',
                    ),
                ),
            ],
            options={
                'permissions': '',
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=150, verbose_name='Team name')),
                (
                    'stream', models.CharField(
                        choices=[
                            ('S', 'Startup'), ('T', 'Strategy'),
                            ('X', 'Technology'),
                        ], default='S', max_length=1, verbose_name='Stream',
                    ),
                ),
                (
                    'coach', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='teams_coach', to='consultant.Consultant',
                    ),
                ),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sprint.Sprint')),
                ('team_members', models.ManyToManyField(blank=True, null=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('edit_team', 'Edit Sprint Team'), ('view_team', 'View Sprint Team'), ('list_team', 'List Teams')),
                'verbose_name': 'Sprint Team',
                'verbose_name_plural': 'Sprints Teams',
            },
        ),
        migrations.AddField(
            model_name='exoproject',
            name='team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='exo_projects', to='sprint.Team',
            ),
        ),
    ]
