# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import sprint.managers.sprint_manager


class Migration(migrations.Migration):

    replaces = [
        ('sprint', '0001_initial'), ('sprint', '0002_auto_20160414_0712'), ('sprint', '0003_auto_20160414_0920'), ('sprint', '0004_auto_20160414_1351'), ('sprint', '0005_auto_20160418_0716'), ('sprint', '0006_auto_20160418_0806'), ('sprint', '0007_exoproject_description'), ('sprint', '0008_auto_20160419_1129'), (
            'sprint',
            '0009_auto_20160421_0745',
        ), ('sprint', '0010_auto_20160421_0804'), ('sprint', '0011_auto_20160421_0939'), ('sprint', '0012_auto_20160421_1036'), ('sprint', '0013_auto_20160422_0628'), ('sprint', '0014_auto_20160507_0915'), ('sprint', '0015_auto_20160509_0959'), ('sprint', '0016_auto_20160509_1627'), ('sprint', '0017_merge'),
        ('sprint', '0014_auto_20160506_1127'), ('sprint', '0018_merge'), ('sprint', '0019_auto_20160520_1001'), ('sprint', '0020_team_created_by'), ('sprint', '0021_auto_20160602_1313'), ('sprint', '0022_auto_20160603_1010'), ('sprint', '0023_team_meeting_id'), ('sprint', '0024_auto_20161005_0722'), ('sprint', '0023_auto_20161005_0837'), (
            'sprint', '0025_merge',
        ), ('sprint', '0026_auto_20161027_1119'), ('sprint', '0027_auto_20161212_1501'), ('sprint', '0028_auto_20161223_0823'), ('sprint', '0029_auto_20170116_0827'), ('sprint', '0030_auto_20170116_0857'), ('sprint', '0031_sprint_advisor_support'), ('sprint', '0032_remove_sprint_advisor_support'),
    ]

    initial = True

    dependencies = [
        ('consultant', '__first__'),
        ('team', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=150, verbose_name='Initiative name')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exo_projects', to='team.Team')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Initiatives',
                'verbose_name': 'Initiative',
                'ordering': ['name'],
                'permissions': (('edit_exoproject', 'Edit ExoProject'), ('view_exoproject', 'View ExoProject'), ('list_exoproject', 'List ExoProject')),
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                (
                    'project_ptr', models.OneToOneField(
                        auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True, primary_key=True, serialize=False, to='project.Project',
                    ),
                ),
                ('challenges', models.TextField(blank=True, null=True, verbose_name='Challenges')),
                ('goals', models.TextField(blank=True, null=True, verbose_name='Goals')),
            ],
            options={
                'verbose_name_plural': 'Sprints',
                'permissions': '',
                'verbose_name': 'Sprint',
            },
            bases=('project.project',),
        ),
        migrations.AlterModelManagers(
            name='sprint',
            managers=[
                ('objects', sprint.managers.sprint_manager.SprintManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['name'], 'verbose_name': 'Sprint', 'verbose_name_plural': 'Sprints'},
        ),
    ]
