# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_squashed_0032_remove_sprint_advisor_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['name'], 'verbose_name': 'ExO Sprint', 'verbose_name_plural': 'ExO Sprints'},
        ),
    ]
