# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_auto_20160414_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={
                'permissions': (
                    ('edit_team', 'Edit Sprint Team'), ('view_team', 'View Sprint Team'), ('list_team', 'List Teams'), (
                        'full_view', 'Team included',
                    ), ('coach_team', 'Team coach'),
                ), 'verbose_name': 'Sprint Team', 'verbose_name_plural': 'Sprints Teams',
            },
        ),
    ]
