# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-30 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_auto_20180613_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exoproject',
            name='team',
        ),
        migrations.DeleteModel(
            name='ExoProject',
        ),
    ]
