# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_auto_20160414_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={
                'permissions': (
                    ('edit_team', 'Edit Sprint Team'), ('view_team', 'View Sprint Team'), ('list_team', 'List Teams'), ('full_view', 'Team included'), (
                        'coach_team', 'Team coach',
                    ), ('team_list_exoproject', 'List Team: ExO Project'),
                ), 'verbose_name': 'Sprint Team', 'verbose_name_plural': 'Sprints Teams',
            },
        ),
    ]
