# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0004_auto_20160414_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='teams_coach', to='consultant.Consultant', verbose_name='ExO Coach',
            ),
        ),
    ]
