# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0006_auto_20160418_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='exoproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
