# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0008_auto_20160419_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={
                'permissions': (
                    ('full_view', 'Team included'), ('coach_team', 'Team coach'), (
                        'team_list_exoproject', 'List Team: ExO Project',
                    ),
                ), 'verbose_name': 'Team', 'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='teams_coach', to='consultant.Consultant', verbose_name='ExO Coach',
            ),
        ),
    ]
