# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0010_auto_20160421_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={
                'ordering': ['name'], 'permissions': (
                    ('team_full_view', 'Team included'), ('coach_team', 'Team coach'), (
                        'team_list_exoproject', 'List Team: ExO Project',
                    ),
                ), 'verbose_name': 'Team', 'verbose_name_plural': 'Teams',
            },
        ),
    ]
