# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0011_auto_20160421_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exoproject',
            options={
                'permissions': (
                    ('edit_exoproject', 'Edit ExoProject'), ('view_exoproject', 'View ExoProject'), (
                        'list_exoproject', 'List ExoProject',
                    ),
                ), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects',
            },
        ),
    ]
