# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0012_auto_20160421_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exoproject',
            options={
                'ordering': ['name'], 'permissions': (
                    ('edit_exoproject', 'Edit ExoProject'), ('view_exoproject', 'View ExoProject'), (
                        'list_exoproject', 'List ExoProject',
                    ),
                ), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={
                'ordering': ['name'], 'permissions': (
                    ('team_full_view', 'Team included'), ('coach_team', 'Team coach'), (
                        'team_delete_exoproject', 'Team: Delete ExO Project',
                    ),
                ), 'verbose_name': 'Team', 'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AlterField(
            model_name='exoproject',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Project name'),
        ),
    ]
