# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 11:27
from __future__ import unicode_literals

from django.db import migrations
import sprint.managers.sprint_manager


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0013_auto_20160422_0628'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sprint',
            managers=[
                ('objects', sprint.managers.sprint_manager.SprintManager()),
            ],
        ),
    ]
