# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0014_auto_20160507_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={
                'ordering': ['name'], 'permissions': (
                    ('team_full_view', 'Team included'), ('coach_team', 'Team coach'), (
                        'team_delete_exoproject', 'Team: Delete ExO Project',
                    ), ('crud_task', 'Team: Add tasks'),
                ), 'verbose_name': 'Team', 'verbose_name_plural': 'Teams',
            },
        ),
    ]
