# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0016_auto_20160509_1627'),
        ('sprint', '0014_auto_20160507_0915'),
    ]

    operations = [
    ]
