# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0017_merge'),
        ('sprint', '0014_auto_20160506_1127'),
    ]

    operations = [
    ]
