# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0019_auto_20160520_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='created_objects', to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
