# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0022_auto_20160603_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Meeting ID (Zoom)'),
        ),
    ]
