# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0022_auto_20160603_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='challenges',
            field=models.TextField(blank=True, null=True, verbose_name='Challenges'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='Goals'),
        ),
    ]
