# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0023_team_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='stream',
            field=models.CharField(
                choices=[('S', 'Startups'), ('T', 'ExO Strategy')],
                default='S', max_length=1, verbose_name='Stream',
            ),
        ),
    ]
