# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0023_auto_20161005_0837'),
        ('sprint', '0024_auto_20161005_0722'),
    ]

    operations = [
    ]
