# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0025_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={
                'ordering': ['name'], 'permissions': (
                    ('team_full_view', 'Team included'), ('coach_team', 'Team coach'), (
                        'team_delete_exoproject', 'Team: Delete ExO Project',
                    ), ('team_start_meeting', 'Team: Start a meeting'),
                ), 'verbose_name': 'Team', 'verbose_name_plural': 'Teams',
            },
        ),
    ]
