# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0026_auto_20161027_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='stream',
            field=models.CharField(
                choices=[('S', 'Startup Ecosystems'), ('T', 'ExO Lite')],
                default='S', max_length=1, verbose_name='Stream',
            ),
        ),
    ]
