# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0029_auto_20170116_0827'),
        ('team', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AlterField(
            model_name='exoproject',
            name='team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='exo_projects', to='team.Team',
            ),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
