# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0030_auto_20170116_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='advisor_support',
            field=models.URLField(blank=True, null=True),
        ),
    ]
