# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 16:24
from __future__ import unicode_literals

from django.db import migrations
import timezone_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_squashed_0033_auto_20180131_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='timezone',
            field=timezone_utils.fields.TimeZoneField(blank=True, max_length=32, null=True),
        ),
    ]
