# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-10 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('customer', '0003_auto_20180213_1624'), ('customer', '0004_auto_20181218_1506'), ('customer', '0005_auto_20181219_1238'),
                ('customer', '0006_auto_20190115_1001'), ('customer', '0007_remove_customer_city'), ('customer', '0008_auto_20190613_0940')]

    dependencies = [
        ('customer', '0002_squashed_0033_auto_20180131_1725'),
    ]

    operations = [
    ]
