# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-18 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180213_1624'),
    ]

    operations = [

    ]
