# Generated by Django 2.2.4 on 2019-08-26 14:48

from django.db import migrations
import utils.images.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180213_1624_squashed_0008_auto_20190613_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': (('edit_customer', 'Edit Customer information'), ('add_user', 'Add user role'), (
                'remove_customer', 'Remove Customer'), ('list_customer', 'List customer')), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=utils.images.fields.PowerImageField(blank=True, choice_field='selectable_profile_picture', null=True, thumbnails=(
                (24, 24), (48, 48), (96, 96), (144, 144)), upload_to='avatars', verbose_name='profile picture'),
        ),
    ]
