# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-19 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import utils.mixins.location_timezone_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20181218_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='timezone',
            field=utils.mixins.location_timezone_mixin.TimeZoneField(blank=True, null=True),
        ),
    ]
