# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20181219_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
