# Generated by Django 2.2.6 on 2019-10-22 09:25

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
import learning.models.mixins.video_mixin
import model_utils.fields
import utils.descriptors.choices_descriptor_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('typeform_url', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('step_stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microlearning', to='project.StepStream')),
            ],
            options={
                'abstract': False,
            },
            bases=(learning.models.mixins.video_mixin.MicroLearningVideoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserMicroLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('responses', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('N', 'Not available'), ('P', 'Pending'), ('D', 'Done')], default='P', max_length=1)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('microlearning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning.MicroLearning')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microlearnings_responses', to='team.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microlearnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'microlearning', 'team')},
            },
            bases=(utils.descriptors.choices_descriptor_mixin.ChoicesDescriptorMixin, models.Model),
        ),
    ]
