# Generated by Django 2.2.1 on 2019-06-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='follow_type',
            field=models.CharField(choices=[('P', 'On Site'), ('S', 'Streaming'), ('V', 'Virtual')], default='P', max_length=1),
        ),
    ]
