# Generated by Django 2.2.4 on 2019-08-23 07:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190823_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=56), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='created_by_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_by_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
