# Generated by Django 2.2.5 on 2019-09-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190823_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url_image',
            field=models.URLField(default=''),
        ),
    ]
