# Generated by Django 2.2.5 on 2019-09-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('T', 'Talk'), ('B', 'Book launch'), ('W', 'Workshop'), ('S', 'ExO Summit'), ('E', 'Webinar')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('CSC', 'Participant'), ('CSO', 'Organizer'), ('CSS', 'Speaker'), ('CSF', 'Facilitator')], default='CSC', max_length=3),
        ),
    ]
