# Generated by Django 2.2.7 on 2019-11-13 17:24

from django.db import migrations, models

from ..models import Participant
from ..conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20190926_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(
                choices=[('CSC', 'Participant'), ('SUC', 'Collaborator'),
                         ('SUS', 'Speaker'), ('SUF', 'Facilitator'), ('SUO', 'Organizer')
                         ], max_length=3),
        ),
    ]
