# Generated by Django 2.2.7 on 2019-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20191113_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_event_other',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('T', 'OpenExO Talk'), ('W', 'OpenExO Workshop'), ('S', 'OpenExO Summit'), ('O', 'Other')], default='W', max_length=1),
        ),
    ]
