# Generated by Django 2.2.7 on 2019-11-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20191121_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start'], 'permissions': (('edit-event', 'Edit Event'), ('delete-event', 'Delete Event'), ('manage-event', 'Manage Event')), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='_status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Under review'), ('H', 'Public'), ('D', 'Deleted')], default='P', max_length=1),
        ),
    ]
