# Generated by Django 2.2.7 on 2019-11-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20191122_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start'], 'permissions': (('edit-event', 'Edit Event'), ('delete-event', 'Delete Event'), ('manage-event', 'Manage Event'), ('create-event-summit', 'Create Event Summit')), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
