# Generated by Django 2.2.4 on 2019-08-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_squashed_0004_auto_20171016_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
