# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 12:54
from __future__ import unicode_literals

from django.db import migrations

from core.conf import settings


def create_industries(apps, schema_editor):
    Industry = apps.get_model('industry', 'Industry')
    for industry_name in settings.CORE_CH_INDUSTRIES_LIST:
        industry, created = Industry.objects.get_or_create(name=industry_name)


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_industries),
    ]
