# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('industry', '0002_auto_20160222_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='created_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='industry_industry_related', to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='industry',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
