# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 11:13
from __future__ import unicode_literals

from django.db import migrations
import industry.manager


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0003_auto_20170630_1202'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='industry',
            managers=[
                ('objects', industry.manager.IndustryManager()),
            ],
        ),
    ]
