# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-21 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0001_initial'),
    ]

    operations = [
    ]
