# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0002_auto_20190823_0957'),
        ('exo_certification', '0002_certificationcohort_role'),
    ]

    operations = [
    ]
