# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-23 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0002_auto_20190820_1223'),
        ('exo_certification', '0002_auto_20190823_1150'),
    ]

    operations = [
    ]
