# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-26 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0003_merge_20190823_1415'),
        ('exo_certification', '0003_merge_20190826_0854'),
    ]

    operations = [
    ]
