# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0003_merge_20190826_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcohort',
            name='first_price_tier',
            field=models.FloatField(default=0),
        ),
    ]
