# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-25 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exo_certification', '0004_merge_20190823_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='exo_certification_coupon_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
