# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0005_auto_20190825_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='fixed_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
