# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-26 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0006_coupon_fixed_email'),
        ('exo_certification', '0003_merge_20190826_0854'),
    ]

    operations = [
    ]
