# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0007_merge_20190826_1104'),
        ('exo_certification', '0004_merge_20190826_1203'),
    ]

    operations = [
    ]
