# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-31 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0008_merge_20190828_0628'),
        ('exo_certification', '0004_certificationcohort_first_price_tier'),
    ]

    operations = [
    ]
