# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-02 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0009_merge_20190831_1512'),
        ('exo_certification', '0004_certificationrequest_hubspot_deal'),
    ]

    operations = [
    ]
