# Generated by Django 2.2.6 on 2019-10-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo_certification', '0014_auto_20191021_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationrequest',
            name='referrer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
