# Generated by Django 2.2.6 on 2019-10-30 15:54

from django.db import migrations, models
from django.core.management import call_command

import django.db.models.deletion


def load_initial_data(apps, schema_editor):
    call_command('update_or_create_exo_certifications')


class Migration(migrations.Migration):

    dependencies = [
        ('exo_role', '0001_initial'),
        ('exo_certification', '0015_certificationrequest_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exocertification',
            name='certification_role',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='certifications', to='exo_role.CertificationRole'),
        ),
        migrations.RunPython(load_initial_data)
    ]
