# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0046_auto_20190710_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintAutomated',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                     parent_link=True, primary_key=True, serialize=False, to='project.Project')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('accomplish', models.CharField(choices=[('1', 'To reinvent the industry and transform our organization'), ('2', 'To transform our organization so that it’s able to adapt to external industry disruption'), (
                    '3', 'To launch an ExO or multiple ExOs in order to transform the industry')], default='1', max_length=1)),
                ('transform', models.CharField(choices=[('1', 'The organisation as a whole, including all markets and industries in which it is positioned'), (
                    '2', 'A specific business unit focused on a particular industry')], default='1', max_length=1)),
                ('playground', models.CharField(choices=[('1', 'Any industry'), ('2', 'Adjacent industries'), (
                    '3', 'Our current industry, with a goal of creating an ExO')], default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Sprint Automated',
                'verbose_name': 'Sprints Automated',
                'ordering': ['name'],
            },
            bases=('project.project',),
        ),
    ]
