# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-13 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_automated', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprintautomated',
            options={'ordering': ['name'], 'verbose_name': 'ExO Automated Sprint', 'verbose_name_plural': 'ExO Automated Sprints'},
        ),
    ]
