# Generated by Django 2.1.7 on 2019-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20181218_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='_type',
            field=models.CharField(choices=[('O', 'Opportunities')], max_length=1),
        ),
    ]
