# Generated by Django 2.1.7 on 2019-03-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationuser',
            name='profile_url',
            field=models.URLField(default=''),
        ),
    ]
