# Generated by Django 2.2 on 2019-05-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0010_auto_20190506_1405'),
        ('conversations', '0010_auto_20190426_1323'),
    ]

    operations = [
    ]
