# Generated by Django 2.2 on 2019-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_merge_20190507_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
