# Generated by Django 2.2.1 on 2019-06-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_auto_20190513_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
