# Generated by Django 2.2.3 on 2019-08-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0014_conversation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationuser',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='conversationuser',
            name='profile_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
