# Generated by Django 2.2.3 on 2019-08-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0016_auto_20190802_0547'),
        ('conversations', '0016_auto_20190808_1113'),
    ]

    operations = [
    ]
