# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import validation.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'validation_type', models.CharField(
                        choices=[
                            ('W', 'Warning'), ('E', 'Error'),
                        ], default='W', max_length=1,
                    ),
                ),
                ('status', models.CharField(choices=[('P', 'Pending'), ('F', 'Fixed')], default='P', max_length=1)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                (
                    'content_type', models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType',
                    ),
                ),
                (
                    'project', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='validations', to='project.Project',
                    ),
                ),
                (
                    'validation_detail', models.CharField(
                        blank=True, choices=[
                            ('NT', 'No team'), ('NZ', 'No Zoom'), ('PP', 'Password default'), ('NS', 'No survey'), ('NQ', 'No ExQ'), ('NC', 'No date'), (
                                'NM', 'No head coach/trainer',
                            ), ('AP', 'Assignments private'), ('AN', 'Assignment without day'), ('NA', 'Project not start'), ('NY', 'Project not city'), ('NG', 'Project not agenda'), ('NF', 'Project typeform'),
                        ], max_length=2, null=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='validation',
            managers=[
                ('objects', validation.manager.ValidationManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='validation',
            options={'verbose_name': 'Validation'},
        ),
    ]
