# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_squashed_0006_auto_20170710_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='validation_detail',
            field=models.CharField(blank=True, choices=[('NT', 'No team'), ('NZ', 'No Zoom'), ('PP', 'Password default'), ('NS', 'No survey'), ('NQ', 'No ExQ'), ('NC', 'No date'), ('NM', 'No head coach/trainer'), ('AP', 'Assignments private'), (
                'AN', 'Assignment without day'), ('NA', 'Project not start'), ('NY', 'Project not city'), ('NG', 'Project not agenda'), ('NF', 'Project typeform'), ('FT', 'Fastrack sprint not supported yet')], max_length=2, null=True),
        ),
    ]
