# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from django.core.management import call_command

import django.db.models.deletion
from django.core.management import call_command
import django.utils.timezone
import keywords.manager
import model_utils.fields
import tagulous.models.fields
import tagulous.models.models


def create_initial_keywords(apps, schema_editor):
    call_command('load_expertise', 'utils/management/commands/expertise.txt')
    call_command('load_technologies', 'utils/scrapy/technologies.json')


def create_tag_for_profile(apps, schema_editor):
    Keyword = apps.get_model('keywords', 'Keyword')
    exoAttributes = settings.CORE_EXO_ATTRIBUTES
    exoIndustries = list(settings.CORE_CH_INDUSTRIES_LIST)
    name = exoAttributes + exoIndustries

    for k1 in Keyword.objects.filter(public=True).exclude(name__in=name):
        k1.tags.add(settings.KEYWORDS_CH_PROFILE)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
                (
                    'created_by', models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='keywords_keyword_related', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', keywords.manager.KeywordManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tagulous_Keyword_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(
                    default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(
                    default=False, help_text='Will not be deleted when the count reaches 0')),
                ('path', models.TextField()),
                ('label', models.CharField(help_text='The name of the tag, without ancestors', max_length=255)),
                ('level', models.IntegerField(default=1, help_text='The level of the tag in the tree')),
                (
                    'parent', models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='children', to='keywords.Tagulous_Keyword_tags',
                    ),
                ),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagTreeModel, models.Model),
        ),
        migrations.AlterModelManagers(
            name='keyword',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='tags',
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True, force_lowercase=True,
                help_text='Enter a comma-separated tag string',
                to='keywords.Tagulous_Keyword_tags',
                tree=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_keyword_tags',
            unique_together={('slug', 'parent')},
        ),
        migrations.RunPython(
            code=create_initial_keywords,
        ),
        migrations.RunPython(
            code=create_tag_for_profile,
        ),
    ]
