# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-18 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('R', 'Requested'),
                                                     ('F', 'Finished')], default='R', max_length=1)),
                ('motivation', models.CharField(choices=[('1', 'Finding the right business model that connects you to an economy of abundance rather than scarcity'), ('2', 'Shifting the mindset of our organization from efficiency-based thinking to a focus on innovation'), ('3', 'Build and retain innovation capacity within your organization'), (
                    '4', 'Neutralize your organizational immune system'), ('5', 'Access knowledge from outside your organization'), ('6', 'Practice using the processes, tools and techniques required for your organization to keep pace'), ('7', 'Change your culture through personal and professional transformation'), ('8', 'Predict the future by creating it'), ('9', 'Other')], default='1', max_length=1)),
                ('goal', models.CharField(choices=[('G', 'To be guided in my Sprint process'), ('S', 'To guide myself or run a self guided in-house Sprint'), ('T', 'A sprint team in person'),
                                                   ('R', 'A sprint team through online remote access'), ('C', 'Access to the online Sprint course and video content')], default='G', max_length=1)),
                ('employees', models.CharField(blank=True, choices=[
                 ('1', '0-50'), ('2', '51-200'), ('3', '201-800'), ('4', '800+')], default='1', max_length=1, null=True)),
                ('initiatives', models.CharField(
                    choices=[('1', '0-10'), ('2', '10-20'), ('3', '20+')], default='1', max_length=1, blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='marketplace_servicerequest_related', to=settings.AUTH_USER_MODEL)),
                ('book', models.BooleanField(default=False)),
                ('participant', models.CharField(choices=[
                 ('C', 'Company'), ('G', 'Government Institution'), ('I', 'Individual')], default='C', max_length=1)),
                ('comment', models.TextField(default='')),
                ('motivation_other', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(default='', max_length=254)),
                ('last_name', models.CharField(default='', max_length=254)),
                ('position', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Service Requests',
                'verbose_name_plural': 'Service Request',
            },
        ),
    ]
