# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='country',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='last_name',
            field=models.CharField(max_length=254),
        ),
    ]
