# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-06 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='location',
        ),
    ]
