# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0046_auto_20190710_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastrackSprint',
            fields=[
                (
                    'project_ptr', models.OneToOneField(
                        auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True, primary_key=True, serialize=False, to='project.Project',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Fastrack Sprints',
                'ordering': ['name'],
                'verbose_name': 'Fastrack Sprint',
            },
            bases=('project.project',),
        ),
    ]
