# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 15:51
from __future__ import unicode_literals

from django.db import migrations
import fastrack.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fastrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fastracksprint',
            managers=[
                ('objects', fastrack.manager.FastrackSprintManager()),
            ],
        ),
    ]
