# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastrack', '0002_auto_20180213_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastracksprint',
            options={'ordering': ['name'], 'verbose_name': 'Fastrack', 'verbose_name_plural': 'Fastrack'},
        ),
    ]
