# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-13 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastrack', '0003_auto_20180424_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastracksprint',
            options={'ordering': ['name'], 'verbose_name': 'Fastrack', 'verbose_name_plural': 'Fastracks'},
        ),
    ]
