# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 08:31
from __future__ import unicode_literals

from django.db import migrations, models

import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='ExOActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'code', models.CharField(
                        choices=[
                            ('coaching_organizations', 'coaching_organizations'),
                            ('advising_and_consulting', 'advising_and_consulting'),
                            ('speaking_and_enlightening', 'speaking_and_enlightening'),
                            ('collaborating_community', 'collaborating_community'),
                            ('coordinating_local_projects', 'coordinating_local_projects'),
                            ('growing_local_community', 'growing_local_community'),
                        ], max_length=150,
                    ),
                ),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'ExOActivities',
                'verbose_name': 'ExOActivity',
            },
        ),
        migrations.AddField(
            model_name='exoactivity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exoactivity',
            name='code',
            field=models.CharField(
                choices=[
                    ('advising', 'advising'),
                    ('coaching', 'coaching'),
                    ('consulting', 'consulting'),
                    ('speaking', 'speaking'),
                    ('business_development', 'business_development'),
                    ('content_generation', 'content_generation'),
                    ('investor', 'investor'),
                    ('entrepreneurship', 'entrepreneurship'),
                    ('training', 'training'),
                    ('company_development', 'company_development'),
                ], max_length=150,
            ),
        ),
        migrations.AlterModelOptions(
            name='exoactivity',
            options={
                'ordering': ['order'], 'permissions': (
                    ('advising', 'Advising'),
                    ('coaching', 'Coaching'),
                    ('consulting', 'Consulting'),
                    ('speaking', 'Speaking'),
                    ('business_development', 'Business development'),
                    ('content_generation', 'Content generation'),
                    ('investor', 'Investor'),
                    ('entrepreneurship', 'Entrepreneurship'),
                    ('training', 'Training'),
                    ('company_development', 'Company development'),
                ), 'verbose_name': 'ExOActivity', 'verbose_name_plural': 'ExOActivities',
            },
        ),
    ]
