# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-23 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_activity', '0002_exoactivity_require_certification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exoactivity',
            options={'ordering': ['order'], 'permissions': (('advising', 'Advising'), ('coaching', 'Coaching'), ('consulting', 'Consulting'), ('speaking', 'Speaking'), ('business_development', 'Business development'), (
                'content_generation', 'Content generation'), ('investor', 'Investor'), ('entrepreneurship', 'Entrepreneurship'), ('training', 'Training'), ('company_development', 'Company development'))},
        ),
    ]
