# Generated by Django 2.2.6 on 2019-10-23 10:37

from django.db import migrations
from django.core.management import call_command


def update_or_create_exo_activities(apps, schema_editor):
    call_command('update_or_create_exo_activities')


class Migration(migrations.Migration):

    dependencies = [
        ('exo_activity', '0003_auto_20190523_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exoactivity',
            name='require_certification',
        ),
        migrations.RunPython(
            code=update_or_create_exo_activities,
        ),
    ]
