# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import permissions.models.base_mixin
import team.models.team
import team.models.team_mixins
import utils.models.slug_field
import zoom_project.models.zoom_mixin


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('consultant', '__first__'),
        ('project', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=150, verbose_name='Team name')),
                (
                    'stream', models.CharField(
                        choices=[
                            ('S', 'Edge Stream'), (
                                'T',
                                'Core Stream',
                            ),
                        ], default='S', max_length=1, verbose_name='Stream',
                    ),
                ),
                ('meeting_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Meeting ID (Zoom)')),
                (
                    'coach', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='teams_coach', to='consultant.Consultant', verbose_name='ExO Coach',
                    ),
                ),
                (
                    'collaborators', models.ManyToManyField(
                        blank=True,
                        related_name='teams_collaborator', to='consultant.Consultant',
                    ),
                ),
                (
                    'created_by', models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='team_team_related', to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='teams', to='project.Project')),
                ('team_members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
                (
                    'slug', utils.models.slug_field.TagAutoSlugField(
                        always_update=True,
                        editable=False, populate_from=team.models.team.create_slug_team, unique=True,
                    ),
                ),
            ],
            options={
                'permissions': (('team_full_view', 'Team included'), ('coach_team', 'Team coach'), ('consultant_team', 'Team consultant'), ('team_delete_exoproject', 'Team: Delete ExO Project'), ('team_start_meeting', 'Team: Start a meeting')),
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
            bases=(
                permissions.models.base_mixin.PermissionManagerMixin,
                team.models.team_mixins.TeamCoachMixin,
                team.models.team_mixins.TeamMemberMixin,
                zoom_project.models.zoom_mixin.ZoomifyMixin, models.Model,
            ),
        ),
    ]
