# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_squashed_0010_auto_20170710_0717'),
    ]

    operations = [
    ]
