# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-12 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20190710_0710'),
        ('team', '0002_auto_20180424_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='project.Step')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='team.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
