# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-15 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teamstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='meeting_id',
        ),
    ]
