# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-24 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_team_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_coach', to='consultant.Consultant', verbose_name='ExO Coach'),
        ),
    ]
