# Generated by Django 2.2.5 on 2019-09-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20190424_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
