# Generated by Django 2.2.5 on 2019-09-16 04:42

from django.db import migrations
import uuid


def create_uuid(apps, schema_editor):
    Team = apps.get_model('team', 'Team')
    for team in Team.objects.filter(uuid__isnull=True):
        team.uuid = uuid.uuid4()
        team.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_team_uuid'),
    ]

    operations = [
        migrations.RunPython(create_uuid),
    ]
