# Generated by Django 2.2.6 on 2019-12-04 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0011_auto_20191128_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('opportunity_uuid', models.UUIDField()),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_related', to='event.Participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
