# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-26 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import permissions.models.base_mixin


def create_initial_organizations(apps, schema_editor):
    InternalOrganization = apps.get_model('custom_auth', 'InternalOrganization')
    names = [
        'OpenExO', 'ExO Works', 'FTI',
    ]
    for name in names:
        InternalOrganization.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Internal Organization',
                'verbose_name_plural': 'Internal Organizations',
                'permissions': (('admin_internal_organization', 'Admin role in organization'), ('regular_internal_organization', 'Regular role in organization')),
            },
            bases=(permissions.models.base_mixin.PermissionManagerMixin, models.Model),
        ),
        migrations.RunPython(create_initial_organizations),
    ]
