# Generated by Django 2.2.6 on 2019-11-07 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


def remove_current_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exo_role', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='related_uuid',
        ),
        migrations.RemoveField(
            model_name='job',
            name='role_code',
        ),
        migrations.RunPython(remove_current_data),
        migrations.AddField(
            model_name='job',
            name='exo_role',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='jobs',
                to='exo_role.ExORole'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='status_detail',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='jobs', to='exo_role.Category'),
        ),
        migrations.CreateModel(
            name='CoreJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='contenttypes.ContentType'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
