# Generated by Django 2.2.7 on 2019-11-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20191107_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
