# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import permissions.models.base_mixin
import relation.managers.consultant_exo_activity
import relation.managers.consultant_exo_area
import relation.managers.consultant_industry
import relation.managers.consultant_keyword
import relation.managers.consultant_project
import relation.managers.project_user
import relation.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '__first__'),
        ('project', '__first__'),
        ('customer', '0001_initial'),
        ('exo_activity', '__first__'),
        ('exo_attributes', '0002_auto_20170703_0655'),
        ('consultant', '__first__'),
        ('industry', '0001_squashed_0004_auto_20171016_1113'),
        ('keywords', '__first__'),
        ('exo_area', '0002_auto_20171130_1807'),
        ('learning', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'consultant', models.ForeignKey(
                        blank=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='roles', to='consultant.Consultant',
                    ),
                ),
                (
                    'project', models.ForeignKey(
                        blank=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='consultants_roles', to='project.Project',
                    ),
                ),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Consultant Roles',
                'verbose_name': 'Consultant Role',
            },
        ),
        migrations.CreateModel(
            name='CustomerUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'customer', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='users_roles', to='customer.Customer',
                    ),
                ),
                (
                    'user', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='customers_roles', to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('role', models.CharField(default='', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1)),
                ('position', models.CharField(default='', max_length=200, null=True, verbose_name='Position')),
            ],
            options={
                'verbose_name_plural': 'Consultant Users Roles',
                'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
                'verbose_name': 'Consultant User Role',
            },
        ),
        migrations.CreateModel(
            name='PartnerProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('role', models.CharField(default='', max_length=1)),
                (
                    'partner', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='projects_roles', to='partner.Partner',
                    ),
                ),
                (
                    'project', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='partners_roles', to='project.Project',
                    ),
                ),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Partner Projects Roles',
                'verbose_name': 'Partner Project Role',
            },
        ),
        migrations.CreateModel(
            name='PartnerUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('role', models.CharField(default='', max_length=1)),
                (
                    'partner', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='users_roles', to='partner.Partner',
                    ),
                ),
                (
                    'user', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='partners_roles', to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1)),
                ('position', models.CharField(default='', max_length=200, null=True, verbose_name='Position')),
            ],
            options={
                'verbose_name_plural': 'Partner Users Roles',
                'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
                'verbose_name': 'Partner User Role',
            },
        ),
        migrations.AlterUniqueTogether(
            name='customeruserrole',
            unique_together={('user', 'customer', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='partnerprojectrole',
            unique_together={('project', 'partner', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='partneruserrole',
            unique_together={('user', 'partner', 'role')},
        ),
        migrations.CreateModel(
            name='UserProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1)),
                (
                    'project', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='users_roles', to='project.Project',
                    ),
                ),
                (
                    'user', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='projects_member', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'User Projects Roles',
                'verbose_name': 'User Project Role',
            },
            bases=(relation.models.mixins.InvitationPublicURLMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='userprojectrole',
            options={
                'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
                'verbose_name': 'User Project Role', 'verbose_name_plural': 'User Projects Roles',
            },
        ),
        migrations.AlterModelOptions(
            name='consultantprojectrole',
            options={
                'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
                'verbose_name': 'Consultant Role', 'verbose_name_plural': 'Consultant Roles',
            },
        ),
        migrations.AlterModelManagers(
            name='consultantprojectrole',
            managers=[
                ('objects', relation.managers.consultant_project.ConsultantProjectRoleManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprojectrole',
            managers=[
                ('objects', relation.managers.project_user.ProjectUserRoleManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantTrained',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'consultant', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trained_sessions', to='consultant.Consultant',
                    ),
                ),
                (
                    'created_by', models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='relation_consultanttrained_related', to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'training_session', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attendants', to='learning.TrainingSession',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'consultant', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exo_roles', to='consultant.Consultant',
                    ),
                ),
                (
                    'created_by', models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='relation_consultantrole_related', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customeruserrole',
            options={
                'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
                'verbose_name': 'Customer User Role', 'verbose_name_plural': 'Customer Users Roles',
            },
        ),
        migrations.CreateModel(
            name='PartnerCustomerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('role', models.CharField(default='', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1)),
                (
                    'customer', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='partners_roles', to='customer.Customer',
                    ),
                ),
                (
                    'partner', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='customer_roles', to='partner.Partner',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Partner Customer Roles',
                'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
                'verbose_name': 'Partner Customer Role',
            },
            bases=(
                relation.models.mixins.InvitationPublicURLMixin,
                permissions.models.base_mixin.PermissionManagerMixin, models.Model,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='partnercustomerrole',
            unique_together={('customer', 'partner', 'role')},
        ),
        migrations.CreateModel(
            name='ConsultantIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('level', models.IntegerField(choices=[(1, 'Intermediate'), (2, 'Advanced'), (3, 'Thought leader')])),
                (
                    'consultant', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='industries', to='consultant.Consultant',
                    ),
                ),
                (
                    'industry', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='consultants', to='industry.Industry',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultantExOAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'level', models.IntegerField(
                        choices=[
                            (0, "I haven't read about it"), (1, 'I have read about it and understand it'), (2, 'I have studied it in some detail'), (
                                3, 'I have implemented this once or twice',
                            ), (4, 'I have implemented this several times'), (5, 'I’m considered a thought leader in this domain'),
                        ], default=0,
                    ),
                ),
                (
                    'consultant', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exo_attributes', to='consultant.Consultant',
                    ),
                ),
                (
                    'exo_attribute', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='consultants', to='exo_attributes.ExOAttribute',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='consultantindustry',
            managers=[
                ('objects', relation.managers.consultant_industry.ConsultantIndustryManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('level', models.IntegerField(choices=[(3, 'Can inspire'), (2, 'Can teach'), (1, 'Can speak')])),
                (
                    'consultant', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='keywords', to='consultant.Consultant',
                    ),
                ),
                (
                    'keyword', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='consultants', to='keywords.Keyword',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', relation.managers.consultant_keyword.ConsultantKeywordManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantExOArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('comment', models.TextField(blank=True, null=True)),
                (
                    'consultant', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exo_areas', to='consultant.Consultant',
                    ),
                ),
                (
                    'exo_area', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='consultants', to='exo_area.ExOArea',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='consultantexoarea',
            managers=[
                ('objects', relation.managers.consultant_exo_area.ConsultantExOAreaManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'status', models.CharField(
                        choices=[
                            ('A', 'Enabled'),
                            ('D', 'Disabled'), ('P', 'Pending'),
                        ], default='P', max_length=1,
                    ),
                ),
                (
                    'consultant_profile', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exo_activities', to='consultant.ConsultantExOProfile',
                    ),
                ),
                (
                    'exo_activity', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='consultants', to='exo_activity.ExOActivity',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Consultant Activities',
                'verbose_name': 'Consultant Activity',
            },
            managers=[
                ('objects', relation.managers.consultant_exo_activity.ConsultantExOActivityManager()),
            ],
        ),
    ]
