# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-26 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import permissions.models.base_mixin
import relation.models.mixins
import utils.descriptors.choices_descriptor_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relation', '0002_hubuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(default='', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='users_roles', to='custom_auth.InternalOrganization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='organizations_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internal OrganizationUser Role',
                'verbose_name_plural': 'Internal Organization Users Roles',
                'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
            },
            bases=(relation.models.mixins.InvitationPublicURLMixin,
                   utils.descriptors.choices_descriptor_mixin.ChoicesDescriptorMixin,
                   permissions.models.base_mixin.PermissionManagerMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='organizationuserrole',
            unique_together={('user', 'organization', 'role')},
        ),
    ]
