# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0003_consultantrolecertificationgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantrole',
            name='certification_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_roles', to='relation.ConsultantRoleCertificationGroup'),
        ),
        migrations.AlterField(
            model_name='consultantrolecertificationgroup',
            name='_type',
            field=models.CharField(choices=[('consultantrole-ambassador', 'Ambassador'), ('consultantrole-coach', 'Coach'), ('consultantrole-trainer', 'Trainer')], max_length=100),
        ),
    ]
