# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-05 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0003_auto_20181026_1215'),
        ('relation', '0004_auto_20181025_1006'),
    ]

    operations = [
    ]
