# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-06 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0005_merge_20181105_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantrolecertificationgroup',
            name='issued_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
