# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-07 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20160210_0854'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relation', '0006_consultantrolecertificationgroup_issued_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultantprojectrole',
            options={'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
                     'verbose_name': 'Consultant Project Role', 'verbose_name_plural': 'Consultant Project Roles'},
        ),
    ]
