# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-15 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_auto_20160210_0854'),
        ('relation', '0007_auto_20181108_1209'),
    ]

    operations = [
    ]
