# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-19 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0008_auto_20181115_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantrolecertificationgroup',
            name='_type',
            field=models.CharField(choices=[('consultantrole-ambassador', 'ExO Ambassador'), ('consultantrole-coach', 'ExO Coach'),
                                            ('consultantrole-trainer', 'ExO Trainer'), ('consultantrole-align-trainer', 'ExO Align Trainer')], max_length=100),
        ),
    ]
