# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0009_auto_20181219_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprojectrole',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customeruserrole',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationuserrole',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partnercustomerrole',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partnerprojectrole',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partneruserrole',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprojectrole',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
