# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-30 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0010_auto_20190530_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantrolecertificationgroup',
            name='_type',
            field=models.CharField(choices=[('consultantrole-ambassador', 'ExO Ambassador'), ('consultantrole-coach', 'ExO Coach'), ('consultantrole-trainer', 'ExO Workshop Trainer'), ('consultantrole-exo-trainer', 'ExO Trainer'), ('consultantrole-align-trainer', 'ExO Align Trainer')], max_length=100),
        ),
    ]
