# Generated by Django 2.2.4 on 2019-08-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0011_auto_20190730_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantrolecertificationgroup',
            name='_type',
            field=models.CharField(choices=[('consultantrole-foundations', 'ExO Foundations'), ('consultantrole-consultant', 'ExO Consultant'), ('consultantrole-ambassador', 'ExO Ambassador'), ('consultantrole-coach',
                                                                                                                                                                                                  'ExO Coach'), ('consultantrole-trainer', 'ExO Workshop Trainer'), ('consultantrole-exo-trainer', 'ExO Trainer'), ('consultantrole-align-trainer', 'ExO Align Trainer')], max_length=100),
        ),
    ]
