# Generated by Django 2.2.6 on 2019-10-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exo_role', '0001_initial'),
        ('relation', '0012_auto_20190826_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantrole',
            name='certification_role',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='consultants_certified', to='exo_role.CertificationRole'),
        ),
        migrations.AlterField(
            model_name='consultantrolecertificationgroup',
            name='_type',
            field=models.CharField(
                choices=[('consultantrole-foundations', 'ExO Foundations'), ('consultantrole-consultant', 'ExO Consultant'),
                         ('consultantrole-ambassador', 'ExO Ambassador'), ('consultantrole-sprint-coach', 'ExO Sprint Coach'),
                         ('consultantrole-trainer', 'ExO Workshop Trainer'), ('consultantrole-exo-trainer', 'ExO Trainer'),
                         ('consultantrole-align-trainer', 'ExO Align Trainer'),
                         ('consultantrole-board-advisor', 'ExO Board Advisor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='consultantrole',
            name='consultant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='consultant_roles',
                to='consultant.Consultant'),
        ),
        migrations.AddField(
            model_name='consultantprojectrole',
            name='exo_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='consultants_roles', to='exo_role.ExORole'),
        ),
        migrations.AddField(
            model_name='userprojectrole',
            name='exo_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_project_roles', to='exo_role.ExORole'),
        ),
    ]
