# Generated by Django 2.2.6 on 2019-10-28 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0004_auto_20190826_1448'),
        ('customer', '0004_auto_20190826_1448'),
        ('custom_auth', '0001_initial'),
        ('relation', '0013_auto_20191023_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationuserrole',
            options={'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
                     'verbose_name': 'Internal Organization User', 'verbose_name_plural': 'Internal Organization Users'},
        ),
        migrations.AlterModelOptions(
            name='partnercustomerrole',
            options={'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
                     'verbose_name': 'Partner Customer', 'verbose_name_plural': 'Partner Customers'},
        ),
        migrations.AlterUniqueTogether(
            name='organizationuserrole',
            unique_together={('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='partnercustomerrole',
            unique_together={('customer', 'partner')},
        ),
        migrations.AlterUniqueTogether(
            name='partneruserrole',
            unique_together={('user', 'partner')},
        ),
        migrations.RemoveField(
            model_name='organizationuserrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='partnercustomerrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='partneruserrole',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='customeruserrole',
            options={'permissions': (('active_role', 'Can activate a role'), ('cancel_role', 'Can cancel a role')),
                     'verbose_name': 'Customer User', 'verbose_name_plural': 'Customer Users'},
        ),
        migrations.AlterModelOptions(
            name='partnerprojectrole',
            options={'verbose_name': 'Partner Project', 'verbose_name_plural': 'Partner Projects'},
        ),
        migrations.AlterUniqueTogether(
            name='customeruserrole',
            unique_together={('user', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='partnerprojectrole',
            unique_together={('project', 'partner')},
        ),
        migrations.RemoveField(
            model_name='customeruserrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='partnerprojectrole',
            name='role',
        ),
    ]
