from django.conf import settings


GROUPS = [
    settings.TOOLS_GROUP_NAME,
    settings.FRONTEND_DEMO_GROUP_NAME,
    settings.REGISTRATION_GROUP_NAME,
    settings.MAIL_NETWORK_LIST_MAIL_GROUP,
    settings.MAIL_SUPPORT_LIST_MAIL_GROUP,
    settings.MAIL_FINANCIAL_LIST_MAIL_GROUP,
    settings.CONSULTANT_WAITING_LIST_GROUP_NAME,
    settings.FRONTEND_DELIVERY_MANAGER_GROUP,
    settings.OPPORTUNITIES_GROUP_NAME,
]
