# Generated by Django 2.2.5 on 2019-09-20 11:28

import badge.models.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(blank=True, choices=[('M', 'Head Coach'), ('X', 'Sprint Coach'), ('S', 'Awake Speaker'), ('I', 'Align Trainer'), ('C', 'Advisor'), ('D', 'Disruptor'), ('DS', 'Disruptor Speaker'), ('SA', 'Sprint Admin'), ('SC', 'Sprint Contributor'), ('UR', 'Sprint Participant'), ('T', 'Workshop Trainer'), ('SW', 'Workshop Speaker'), ('CWA', 'Swarm Advisor'), ('A', 'Team Leader'), (
                    'B', 'Team Member'), ('E', 'Curator'), ('H', 'Co-Curator'), ('J', 'Solution Accelerator'), ('F', 'Observer/Evaluator'), ('G', 'Local Team Member'), ('CSC', 'Collaborator'), ('CSS', 'Speaker'), ('CSF', 'Facilitator'), ('CSO', 'Organizer'), ('CCC', 'Content Creator'), ('CCB', 'Community Builder'), ('EF', 'Advisor'), ('D', 'Disruptor'), ('EC', 'Consultant'), ('CMO', 'Other')], max_length=5, null=True)),
                ('category', models.CharField(choices=[('CS', 'ExO Sprint'), ('CW', 'ExO Workshop'), ('CF', 'Fastrack'), (
                    'CA', 'ExO Swarm'), ('CM', 'ExO Summits'), ('CC', 'Community'), ('CT', 'Marketplace')], default='CS', max_length=2)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='badge_userbadge_related', related_query_name='badge_userbadges', to='badge.Badge')),
            ],
            options={
                'abstract': False,
            },
            bases=(badge.models.mixins.ActionLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserBadgeActivity',
            fields=[
                ('userbadge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True, serialize=False, to='badge.UserBadge')),
            ],
            options={
                'abstract': False,
            },
            bases=('badge.userbadge',),
        ),
        migrations.CreateModel(
            name='UserBadgeJob',
            fields=[
                ('userbadge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True, serialize=False, to='badge.UserBadge')),
            ],
            options={
                'abstract': False,
            },
            bases=('badge.userbadge',),
        ),
        migrations.CreateModel(
            name='UserBadgeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('user_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='user_badge_items', to='badge.UserBadge')),
            ],
            options={
                'abstract': False,
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='userbadge',
            name='items',
            field=models.ManyToManyField(related_name='user_badges',
                                         through='badge.UserBadgeItem', to='badge.UserBadge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_userbadge_related',
                                    related_query_name='badge_userbadges', to=settings.AUTH_USER_MODEL),
        ),
    ]
