# Generated by Django 2.2.5 on 2019-09-20 11:28

from django.db import migrations, models
from django.core.management import call_command


def create_initial_badges(apps, schema_editor):
    call_command('update_or_create_badges')


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
        ('exo_role', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(
                choices=[('CC', 'Community'), ('SP', 'ExO Sprint'), ('FA', 'Fastrack'), ('WO', 'Workshop'), ('SW', 'Swarm'), ('SU', 'Summit'), (
                    'AC', 'Advisory Call'), ('DS', 'Disruption Session'), ('TA', 'Keynote presentation'), ('CP', 'Certification Program'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.CharField(
                blank=True,
                choices=[('CCC', 'Content Creator'), ('CCB', 'Community Builder'), ('SHC', 'Head Coach'), ('SSH', 'Sprint Coach'), ('SAS', 'Awake Speaker'), ('SAT', 'Align Trainer'), ('SAD', 'Advisor'), ('SDI', 'Disruptor'), ('SDS', 'Disruptor Speaker'), ('SDM', 'Delivery Manager'), ('SPA', 'Sprint Participant'), ('SCO', 'Sprint Contributor'), ('SRE', 'Reporter'), ('SAM', 'Account Manager'), ('SSC', 'Shadow Coach'), ('SOB', 'Observer'), ('SOT', 'Other'), ('FTL', 'Team Leader'), ('FTM', 'Team Member'), ('FCU', 'Curator'), ('FCC', 'Co-Curator'), (
                    'FSA', 'Solution Accelerator'), ('FOE', 'Observer/Evaluator'), ('FLM', 'Local Team Member'), ('FAD', 'Advisor'), ('WSP', 'Speaker'), ('WTR', 'Trainer'), ('SWA', 'Advisor'), ('SUC', 'Collaborator'), ('SUS', 'Speaker'), ('SUF', 'Facilitator'), ('SUO', 'Organizer'), ('ACA', 'Advisor'), ('TAS', 'Speaker'), ('DSD', 'Disruptor'), ('OAD', 'Advisor'), ('OCO', 'Coach'), ('OCN', 'Consultant'), ('OSP', 'Speaker'), ('OTR', 'Trainer'), ('ODR', 'Disruptor'), ('OOO', 'Other'), ('CMT', 'Master Trainer'), ('CMC', 'Mentor Coach'), ('CAD', 'Avisor'), ('CDI', 'Disruptor')], max_length=5, null=True),
        ),
        migrations.RunPython(create_initial_badges)
    ]
