# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import model_utils.fields
import project.managers.project
import project.managers.step


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20160210_0854'),
        ('partner', '0001_squashed_0010_auto_20170523_0748'),
        ('relation', '0001_squashed_0040_consultantactivity'),
        ('consultant', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                (
                    'project_ptr', models.OneToOneField(
                        auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True, primary_key=True, serialize=False, to='project.Project',
                    ),
                ),
                ('languages', models.ManyToManyField(to='core.Language')),
                ('type_event', models.CharField(choices=[
                 ('T', 'ExO Talk'), ('B', 'ExO Book launch'), ('W', 'ExO Workshop'), ('S', 'ExO Summit')], default='W', max_length=1)),
                ('amount', models.FloatField(default=0, null=True)),
                ('currency', models.CharField(choices=[('E', '€'), ('D', '$')], default='E', max_length=1)),
                ('url', models.URLField(blank=True, null=True)),
                ('follow_type', multiselectfield.db.fields.MultiSelectField(choices=[
                 ('P', 'On Site'), ('S', 'Streaming'), ('V', 'Virtual')], default='P', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Talks',
                'verbose_name': 'Talk',
            },
            bases=('project.project',),
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('objects', project.managers.project.ProjectManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='talk',
            managers=[
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={
                'ordering': ['name'], 'permissions': (
                    ('edit_project', 'Edit Project'),
                    ('full_view', 'View Project'),
                    ('crud_team', 'Add/Edit/Delete Team'),
                    ('project_manager', 'Project Manager'),
                    ('project_manage_consultant', 'Manage ExO Consultants'),
                    ('project_consultant', 'Project Consultant'),
                    ('project_assessment', 'Project ExO Assessment'),
                    ('project_settings', 'Project Settings'),
                ), 'verbose_name': 'Service', 'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('index', models.IntegerField()),
                (
                    'status', models.CharField(
                        choices=[
                            ('w', 'Waiting'),
                            ('s', 'Started'), ('d', 'Done'),
                        ], default='w', max_length=1,
                    ),
                ),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='steps',
                    to='project.Project')),
            ],
            options={
                'verbose_name_plural': 'Steps',
                'ordering': ['index'],
                'verbose_name': 'Step',
            },
        ),
        migrations.AlterModelManagers(
            name='step',
            managers=[
                ('objects', project.managers.step.StepManager()),
            ],
        ),
        migrations.CreateModel(
            name='StepStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'stream', models.CharField(
                        choices=[
                            ('S', 'Edge Stream'), (
                                'T',
                                'Core Stream',
                            ),
                        ], default='S', max_length=1, verbose_name='Stream',
                    ),
                ),
                ('goal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Goal')),
                ('guidelines', models.TextField(blank=True, default='', null=True)),
                ('step', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='streams',
                    to='project.Step')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={
                'ordering': ['name'], 'permissions': (
                    ('edit_project', 'Edit Project'),
                    ('full_view', 'View Project'),
                    ('only_view', 'Only view project'),
                    ('crud_team', 'Add/Edit/Delete Team'),
                    ('project_manager', 'Project Manager'),
                    ('project_manage_consultant', 'Manage ExO Consultants'),
                    ('project_consultant', 'Project Consultant'),
                    ('project_assessment', 'Project ExO Assessment'),
                    ('project_settings', 'Project Settings'),
                ), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects',
            },
        ),
    ]
