# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-10 06:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180821_1204'),
        ('relation', '0001_squashed_0040_consultantactivity'),
        ('consultant', '0002_squashed_0057_merge_20171220_1152'),
        ('partner', '0001_squashed_0010_auto_20170523_0748'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_auth', '0001_initial'),
        ('project', '0003_squashed_0044_auto_20170710_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'permissions': (('edit_project', 'Edit Project'), ('full_view', 'View Project'), ('only_view', 'Only view project'), ('crud_team', 'Add/Edit/Delete Team'), ('project_manager', 'Project Manager'), ('project_manage_consultant', 'Manage ExO Consultants'), (
                'project_consultant', 'Project Consultant'), ('project_assessment', 'Project ExO Assessment'), ('project_settings', 'Project Settings'), ('manage_ticket', 'Project Tickets management')), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='consultants',
            field=models.ManyToManyField(blank=True, related_name='projects',
                                         through='relation.ConsultantProjectRole', to='consultant.Consultant'),
        ),
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='projects',
                                         through='relation.PartnerProjectRole', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='projects', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lapse',
            field=models.CharField(blank=True, choices=[(
                'W', 'Week'), ('D', 'Day'), ('P', 'Period'), ('N', 'No step')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='project_project_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='internal_organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='projects', to='custom_auth.InternalOrganization'),
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('launch', django.contrib.postgres.fields.jsonb.JSONField(default={
                 'fix_password': '', 'send_welcome_consultant': False, 'send_welcome_participant': False})),
                ('participant_step_feedback_enabled', models.BooleanField(default=False)),
                ('participant_step_microlearning_enabled', models.BooleanField(default=False)),
                ('team_communication', models.BooleanField(default=True)),
                ('ask_to_ecosystem', models.BooleanField(default=True)),
                ('version', models.CharField(choices=[('1', 'Version 1'),
                                                      ('2', 'Version 2')], default='2', max_length=1)),
                ('template_assignments', models.CharField(default='', max_length=1, null=True)),
                ('join_enabled', models.BooleanField(default=False)),
                ('hide_from_my_jobs', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'permissions': (('edit_project', 'Edit Project'), ('full_view', 'View Project'), ('only_view', 'Only view project'), ('crud_team', 'Add/Edit/Delete Team'), ('project_manager', 'Project Manager'), ('project_manage_consultant', 'Manage ExO Consultants'), (
                'project_consultant', 'Project Consultant'), ('project_assessment', 'Project ExO Assessment'), ('project_settings', 'Project Settings'), ('manage_ticket', 'Project Delivery management')), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='project_settings', to='project.Project'),
        ),
        migrations.AddField(
            model_name='talk',
            name='sub_title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
