# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20180130_1221_squashed_0065_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
