# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-10 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20190710_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='directory',
            field=models.BooleanField(default=True),
        ),
    ]
