# Generated by Django 2.2.4 on 2019-08-26 14:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import project.models.project_setting


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_auto_20190821_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('T', 'Training'), ('C', 'Certification'), ('CC', 'Certification ExO Consultant'), (
                'CX', 'Certification ExO Sprint Coach'), ('D', 'Demo'), ('E', 'Event'), ('M', 'Transformation')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='launch',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=project.models.project_setting.default_launch),
        ),
    ]
