# Generated by Django 2.2.7 on 2019-11-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_auto_20190613_0940'),
        ('team', '0005_auto_20190424_0858'),
        ('exo_certification', '0015_certificationrequest_referrer'),
        ('zoom_project', '0002_zoomroom_zoom_id'),
        ('project', '0069_auto_20190826_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('T', 'Training'), ('C', 'Certification'), ('CC', 'Certification ExO Consultant'), ('CX', 'Certification ExO Sprint Coach'), ('D', 'Demo'), ('M', 'Transformation')], default='M', max_length=2),
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
    ]
