# Generated by Django 2.2.7 on 2019-11-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0069_auto_20190826_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='advisor_request',
            field=models.BooleanField(default=False),
        ),
    ]
