# Generated by Django 2.2.8 on 2019-12-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_projectsettings_advisor_request'),
        ('project', '0071_remove_projectsettings_join_enabled'),
    ]

    operations = [
    ]
