# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 06:55
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


def create_exo_attributes(apps, schema_editor):
    ExOAttribute = apps.get_model('exo_attributes', 'ExOAttribute')
    names_scale = [
        'Staff on Demand', 'Community & Crowd',
        'Algorithms', 'Leveraged Assets', 'Engagement',
    ]
    names_ideas = [
        'Interfaces', 'Dashboards',
        'Experimentation', 'Autonomy', 'Social Technologies',
    ]
    i = 0
    for name in names_scale:
        ExOAttribute.objects.get_or_create(
            name=name,
            order=i,
            _type=settings.EXO_ATTRIBUTES_CH_SCALE,
        )
        i += 1
    i = 0
    for name in names_ideas:
        ExOAttribute.objects.get_or_create(
            name=name,
            order=i,
            _type=settings.EXO_ATTRIBUTES_CH_IDEAS,
        )
        i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('exo_attributes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_exo_attributes),
    ]
