# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 10:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


def create_initial_trainingsession(apps, schema_editor):
    TrainingSession = apps.get_model('learning', 'TrainingSession')
    TrainingSession.objects.create(name='Trained')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
        ('project', '0003_squashed_0044_auto_20170710_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('typeform_url', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                (
                    'step_stream', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='microlearning', to='project.StepStream',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMicroLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('responses', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True)),
                (
                    'status', models.CharField(
                        choices=[
                            ('N', 'Not available'),
                            ('P', 'Pending'), ('D', 'Done'),
                        ], default='P', max_length=1,
                    ),
                ),
                ('score', models.IntegerField(blank=True, null=True)),
                (
                    'microlearning', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='responses', to='learning.MicroLearning',
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='microlearning',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
