# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_squashed_0008_microlearning_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microlearning',
            name='video_url',
            field=models.CharField(max_length=20),
        ),
    ]
