# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20180131_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microlearning',
            old_name='video_url',
            new_name='video_id',
        ),
    ]
