# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_auto_20180201_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microlearning',
            name='video_id',
        ),
    ]
