# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-24 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exo_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('hub', models.OneToOneField(blank=True, null=True,
                                             on_delete=django.db.models.deletion.CASCADE, related_name='circle', to='exo_hub.ExOHub')),
            ],
            options={
                'verbose_name': 'Circle',
                'verbose_name_plural': 'Circle',
            },
        ),
    ]
