# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-24 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={'permissions': (('create_post', 'Create post'),),
                     'verbose_name': 'Circle', 'verbose_name_plural': 'Circle'},
        ),
    ]
