# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_load_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={'ordering': ['name'], 'permissions': (
                ('create_post', 'Create post'),), 'verbose_name': 'Circle', 'verbose_name_plural': 'Circle'},
        ),
    ]
