# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-07 06:22
from __future__ import unicode_literals

import autoslug.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_auto_20180716_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True,
                                                editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
