# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-28 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_auto_20180716_1151'),
        ('circles', '0004_auto_20180719_0549'),
    ]

    operations = [
    ]
