# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-11 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_merge_20180828_0933'),
        ('circles', '0005_circle_slug'),
    ]

    operations = [
    ]
