# Generated by Django 2.2.4 on 2019-08-26 14:48

from django.db import migrations, models

import django.db.models.deletion



def set_default_slug_for_circles(apps, schema_editor):
    Circle = apps.get_model(app_label='circles', model_name='Circle')

    for circle in Circle.objects.all():
        circle.save()


def load_initial_data(apps, schema_editor):
    set_default_slug_for_circles(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0008_auto_20190717_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='hub',
            field=models.OneToOneField(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='circle', to='exo_hub.ExOHub'),
        ),
        migrations.RunPython(load_initial_data),
    ]
