# Generated by Django 2.2.7 on 2019-11-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exo_role', '0001_initial'),
        ('circles', '0009_auto_20190826_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='certification_required',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exo_role.CertificationRole'),
        ),
    ]
