# Generated by Django 2.2.7 on 2019-11-18 16:13

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    call_command('update_or_create_circles')


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0010_circle_certification_required'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
