# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-23 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
    ]
