# Generated by Django 2.2.6 on 2019-10-03 14:20

from django.db import migrations, models
from django.core.management import call_command


def create_initial_industries(apps, schema_editor):
    call_command('update_industries')



class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_populate_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(
            code=create_initial_industries,
        ),
    ]
