# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-03 10:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import registration.models.registration_process_step_email_mixin
import utils.descriptors.choices_descriptor_mixin

from ..process import create_process_template_v1, create_process_template_v3


def create_process_v3(apps, schema_editor):
    create_process_template_v3()


def create_process_v1(apps, schema_editor):
    create_process_template_v1()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('registration', '0001_squashed_0015_auto_20170619_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email_ok', models.TextField(blank=True, null=True)),
                ('email_ok_subject', models.TextField(blank=True, null=True)),
                ('email_ok_body', models.TextField(blank=True, null=True)),
                ('email_ko', models.TextField(blank=True, null=True)),
                ('email_ko_subject', models.TextField(blank=True, null=True)),
                ('email_ko_body', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('A', 'Current'), ('P', 'Pending'),
                                                     ('X', 'Executed'), ('C', 'Declined')], default='P', max_length=1)),
                ('content_type', models.ForeignKey(blank=True, null=True,
                                                   on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('next_steps', models.ManyToManyField(to='registration.ProcessStep')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(utils.descriptors.choices_descriptor_mixin.ChoicesDescriptorMixin,
                   registration.models.registration_process_step_email_mixin.ProcessStepEmailMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProcessTemplateStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('R', 'Roles'), ('S', 'Skills'), ('T', 'Test'), ('A', 'Application'), ('G', 'Agreement'), (
                    'F', 'On boarding'), ('E', 'Team'), ('U', 'Signup'), ('X', 'Simple SignUp'), ('V', 'Survey'), ('K', 'Ticket')], max_length=20)),
                ('email_tpl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.NotificationStep')),
                ('next_steps', models.ManyToManyField(related_name='_previous_steps', to='registration.ProcessTemplateStep')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessTemplateStepOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customizable', models.BooleanField(default=False)),
                ('pre_step', models.BooleanField()),
                ('post_step', models.BooleanField()),
                ('method_name', models.CharField(blank=True, max_length=200, null=True)),
                ('method_kwargs', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('property_name', models.CharField(blank=True, max_length=200, null=True)),
                ('property_value', models.NullBooleanField()),
                ('property_values', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('display_status', models.CharField(blank=True, max_length=100, null=True)),
                ('display', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True,
                                                   on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='registration_registrationprocess_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationProcessTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='StepOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pre_step', models.BooleanField()),
                ('post_step', models.BooleanField()),
                ('method_name', models.CharField(blank=True, max_length=200, null=True)),
                ('method_kwargs', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('property_name', models.CharField(blank=True, max_length=200, null=True)),
                ('property_value', models.NullBooleanField()),
                ('property_values', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='registrationprocess',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='registration.RegistrationProcessTemplate'),
        ),
        migrations.AddField(
            model_name='registrationprocess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='registration_process', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationlog',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='logs', to='registration.RegistrationProcess'),
        ),
        migrations.AddField(
            model_name='processtemplatestep',
            name='options',
            field=models.ManyToManyField(to='registration.ProcessTemplateStepOption'),
        ),
        migrations.AddField(
            model_name='processtemplatestep',
            name='previous_steps',
            field=models.ManyToManyField(related_name='_next_steps', to='registration.ProcessTemplateStep'),
        ),
        migrations.AddField(
            model_name='processtemplatestep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='steps', to='registration.RegistrationProcessTemplate'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='options',
            field=models.ManyToManyField(to='registration.StepOption'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='steps', to='registration.RegistrationProcess'),
        ),
        migrations.RunPython(
            code=create_process_v1,
        ),
        migrations.RunPython(
            code=create_process_v3,
        ),
    ]
