# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-05 10:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190504_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprocess',
            name='entry_point',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
