# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 11:41
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group

from ..conf import settings


def create_initial_group(apps, schema_editor):
    User = get_user_model()
    tool_group, _ = Group.objects.get_or_create(name=settings.TOOLS_GROUP_NAME)
    for user in User.objects.filter(is_superuser=True):
        user.groups.add(tool_group)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_initial_group),
    ]
