# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-25 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0046_auto_20190710_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Project')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Generic Project',
                'verbose_name_plural': 'Generic Projects',
            },
            bases=('project.project',),
        ),
    ]
