# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-13 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_project', '0002_genericproject_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericproject',
            options={'ordering': ['name'], 'verbose_name': 'ExO Generic Project', 'verbose_name_plural': 'ExO Generic Projects'},
        ),
    ]
