# Generated by Django 2.2.4 on 2019-08-26 14:48

from django.db import migrations
import project.managers.project


class Migration(migrations.Migration):

    dependencies = [
        ('generic_project', '0003_auto_20190613_0940'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='genericproject',
            managers=[
                ('objects', project.managers.project.ProjectManager()),
            ],
        ),
    ]
