# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 08:09
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('mimetype', models.CharField(blank=True, max_length=150, null=True)),
                ('_filename', models.CharField(blank=True, max_length=20, null=True)),
                ('read_perms', models.CharField(max_length=1)),
                ('object_id_read', models.PositiveIntegerField()),
                ('write_perms', models.CharField(max_length=1)),
                ('object_id_write', models.PositiveIntegerField()),
                (
                    'content_type_read', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='node_reads', to='contenttypes.ContentType',
                    ),
                ),
                (
                    'content_type_write', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='node_writes', to='contenttypes.ContentType',
                    ),
                ),
                (
                    'created_by', models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'parent', models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.Node',
                    ),
                ),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.Project')),
            ],
            options={
                'verbose_name_plural': 'Nodes',
                'ordering': ['name'],
                'verbose_name': 'Node',
            },
        ),
    ]
