# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 12:00
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.operations
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import sizefield.models
import tagulous.models.fields
import tagulous.models.models
import utils.models.unique_name


class Migration(migrations.Migration):

    replaces = [
        ('files', '0001_initial'), ('files', '0002_auto_20160426_0812'), ('files', '0003_auto_20160426_0846'), ('files', '0004_auto_20160429_0857'), ('files', '0005_auto_20160429_0901'), (
            'files',
            '0006_auto_20160503_1133',
        ), ('files', '0007_auto_20160503_1144'), ('files', '0008_auto_20160504_1535'), ('files', '0009_auto_20160505_0712'), ('files', '0010_auto_20160506_0722'),
        ('files', '0011_node_exo_projects'), ('files', '0015_auto_20160530_1155'), ('files', '0017_node_metadata'), ('files', '0018_auto_20170125_1632'), ('files', '0019_auto_20170213_1512'), (
            'files', '0020_auto_20170329_0805',
        ), ('files', '0021_delete_node'), ('files', '0022_resource_file_size'), ('files', '0023_auto_20170710_0917'), ('files', '0024_auto_20180122_1141'),
    ]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0013_auto_20160422_0628'),
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Resource_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('path', models.TextField()),
                ('label', models.CharField(help_text='The name of the tag, without ancestors', max_length=255)),
                ('level', models.IntegerField(default=1, help_text='The level of the tag in the tree')),
                (
                    'parent', models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='children', to='files.Tagulous_Resource_tags',
                    ),
                ),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagTreeModel, models.Model),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                (
                    'slug', autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False, max_length=200, populate_from='name',
                    ),
                ),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('mimetype', models.CharField(blank=True, max_length=150, null=True)),
                ('_filename', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                (
                    'created_by', models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'tags', tagulous.models.fields.TagField(
                        _set_tag_meta=True, force_lowercase=True,
                        help_text='Enter a comma-separated tag string', to='files.Tagulous_Resource_tags', tree=True,
                    ),
                ),
                ('file_size', sizefield.models.FileSizeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'ordering': ['name'],
                'verbose_name_plural': 'Resources',
            },
            bases=(utils.models.unique_name.UniqueNameMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='Tagulous_Resource_tags',
            unique_together={('slug', 'parent')},
        ),
    ]
