# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 14:18
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_squashed_0024_auto_20180122_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('filename', models.CharField(max_length=255)),
                ('filename_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='filename', unique=True)),
                ('mimetype', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_uploadedfile_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UploadedFile versioned',
                'verbose_name_plural': 'UploadedFiles versioned',
            },
        ),
        migrations.CreateModel(
            name='UploadedFileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('version', models.IntegerField(default=1)),
                ('filestack_status', models.CharField(choices=[('A', 'Active'), ('D', 'Disabled')], default='A', max_length=1)),
                ('filestack_url', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_uploadedfileversion_related', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.UploadedFile')),
            ],
            options={
                'verbose_name': 'UploadedFile version',
                'ordering': ['-version'],
                'verbose_name_plural': 'UploadedFile versions',
            },
        ),
    ]
