# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 17:01
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20180606_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfileversion',
            name='download_hash',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='filename_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='filename', unique=True),
        ),
    ]
