# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20160426_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['id'], 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
