# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20180606_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfileversion',
            name='filestack_status',
            field=models.CharField(choices=[('Stored', 'Active'), ('InTransit', 'InTransit'), ('Failed', 'Failed'), ('Disabled', 'Disabled')], default='Stored', max_length=20),
        ),
    ]
