# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0013_auto_20160422_0628'),
        ('files', '0005_auto_20160429_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExOProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'created_by', models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'exo_project', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files_related', to='sprint.ExoProject',
                    ),
                ),
                (
                    'file', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_related', to='files.Node',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='exo_projects',
            field=models.ManyToManyField(related_name='files', through='files.FileExOProject', to='sprint.ExoProject'),
        ),
    ]
