# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-10 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0005_auto_20180615_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
