# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20160503_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileexoproject',
            name='file',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='projects_related', to='files.Node',
            ),
        ),
    ]
