# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-27 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0006_auto_20190810_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFileVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('P', 'Private'),
                                                         ('G', 'Public with group')], default='P', max_length=1)),
                ('content_type', models.ForeignKey(blank=True, null=True,
                                                   on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='files_uploadedfilevisibility_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uploadedfileversion',
            options={'ordering': ['-version']},
        ),
        migrations.AddField(
            model_name='uploadedfilevisibility',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='visibility', to='files.UploadedFile'),
        ),
    ]
