# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20160504_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
    ]
