# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0013_auto_20160422_0628'),
        ('files', '0010_auto_20160506_0722'),
    ]

    operations = [
    ]
