# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 10:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20160530_1155'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='node',
            name='metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
