# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_auto_20170213_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='content_type_read',
        ),
        migrations.RemoveField(
            model_name='node',
            name='content_type_write',
        ),
        migrations.RemoveField(
            model_name='node',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='node',
            name='owner_content_type',
        ),
        migrations.RemoveField(
            model_name='node',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='node',
            name='project',
        ),
    ]
