# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_auto_20170329_0805'),
    ]

    operations = [
    ]
