# Generated by Django 2.2.6 on 2019-10-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status_detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='job',
            name='related_uuid',
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
