# Generated by Django 2.2.8 on 2019-12-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191029_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
