# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'status', models.CharField(
                        choices=[
                            ('A', 'Active'),
                            ('P', 'Pending'), ('C', 'Cancelled'),
                        ], default='P', max_length=1,
                    ),
                ),
                (
                    'type', models.CharField(
                        choices=[
                            ('R', 'Roles'), ('S', 'Skills'), ('T', 'Test'),
                            ('A', 'Application'), ('S', 'Signup'), ('X', 'Survey'),
                        ], max_length=1,
                    ),
                ),
                ('hash', models.CharField(max_length=512)),
                ('valid_date', models.DateField()),
                (
                    'user', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invitations', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvitationObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                (
                    'invitation', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invitation_objects', to='invitation.Invitation',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='invite_user',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_from',
                to=settings.AUTH_USER_MODEL, verbose_name='This user creates the invitation to user',
            ),
        ),
        migrations.AddField(
            model_name='invitation',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=model_utils.fields.StatusField(
                choices=[(0, 'dummy')], default='P', max_length=100, no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(
                choices=[
                    ('R', 'Roles'), ('S', 'Skills'), ('T', 'Test'),
                    ('A', 'Application'), ('U', 'Signup'), ('V', 'Survey'),
                ], max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='valid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={
                'permissions': (
                    ('accept_invitation', 'Can accept the invitation'), ('cancel_invitation', 'Can cancel/deny the invitation'),
                    ('resend_invitation', 'Can resend the invitation'),
                ), 'verbose_name': 'Invitation', 'verbose_name_plural': 'Invitations',
            },
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(
                choices=[
                    ('R', 'Roles'), ('S', 'Skills'), ('T', 'Test'), (
                        'A',
                        'Application',
                    ), ('U', 'Signup'), ('X', 'Simple SignUp'), ('V', 'Survey'),
                ], max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(
                choices=[
                    ('R', 'Roles'), ('S', 'Skills'), ('T', 'Test'), ('A', 'Application'),
                    ('E', 'Team'), ('U', 'Signup'), ('X', 'Simple SignUp'), ('V', 'Survey'),
                ], max_length=1,
            ),
        ),
        migrations.AddField(
            model_name='invitation',
            name='_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(
                choices=[
                    ('R', 'Roles'), ('S', 'Skills'), ('T', 'Test'), ('A', 'Application'), (
                        'G', 'Agreement',
                    ), ('E', 'Team'), ('U', 'Signup'), ('X', 'Simple SignUp'), ('V', 'Survey'),
                ], max_length=1,
            ),
        ),
        migrations.AddField(
            model_name='invitation',
            name='description_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(
                choices=[
                    ('R', 'Roles'), ('S', 'Skills'), ('T', 'Test'), ('A', 'Application'), ('G', 'Agreement'), (
                        'E', 'Team',
                    ), ('U', 'Signup'), ('X', 'Simple SignUp'), ('V', 'Survey'), ('L', 'User Evaluation'),
                ], max_length=1,
            ),
        ),
        migrations.CreateModel(
            name='InvitationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'log_type', models.CharField(
                        choices=[
                            ('S', 'Status changed'),
                            ('D', 'Notification Sent'),
                        ], default='S', max_length=1,
                    ),
                ),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'invitation', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='logs', to='invitation.Invitation',
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='content_type',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType',
            ),
        ),
        migrations.AddField(
            model_name='invitation',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(
                choices=[
                    ('R', 'Roles'), ('S', 'Skills'), ('T', 'Test'), ('A', 'Application'), ('G', 'Agreement'), (
                        'E', 'Team',
                    ), ('U', 'Signup'), ('X', 'Simple SignUp'), ('V', 'Survey'), ('L', 'User Evaluation'), ('K', 'Ticket'),
                ], max_length=1,
            ),
        ),
        migrations.CreateModel(
            name='RelatedObjectFake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(
                choices=[
                    ('R', 'Roles'), ('S', 'Skills'), ('T', 'Test'), ('A', 'Application'), ('G', 'Agreement'), ('F', 'On boarding'), (
                        'E', 'Team',
                    ), ('U', 'Signup'), ('X', 'Simple SignUp'), ('V', 'Survey'), ('L', 'User Evaluation'), ('K', 'Ticket'),
                ], max_length=1,
            ),
        ),
    ]
