# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_squashed_0017_auto_20170619_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(choices=[('R', 'Roles'), ('S', 'Skills'), ('T', 'Test'), ('A', 'Application'), ('G', 'Agreement'), (
                'F', 'On boarding'), ('E', 'Team'), ('U', 'Signup'), ('X', 'Simple SignUp'), ('V', 'Survey'), ('K', 'Ticket')], max_length=1),
        ),
    ]
