# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeetingstatus',
            name='host_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zoommeetingstatus',
            name='status',
            field=models.CharField(
                blank=True, choices=[
                    ('STARTED', 'Started'),
                    ('ENDED', 'Ended'),
                ], max_length=10, null=True,
            ),
        ),
    ]
