# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_project', '0002_auto_20160930_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeetingstatus',
            name='host_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
