# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 11:19
from __future__ import unicode_literals

from django.db import migrations
import zoom_project.manager


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_project', '0003_auto_20161003_1151'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='zoommeetingstatus',
            managers=[
                ('objects', zoom_project.manager.ZoomMeetingStatusManager()),
            ],
        ),
    ]
