# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_project', '0005_auto_20170417_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoomsettings',
            name='project',
        ),
    ]
