# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_project', '0007_auto_20170418_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomroom',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Meeting ID (Zoom)'),
        ),
    ]
