# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_project', '0008_auto_20170419_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoomroom',
            name='settings',
        ),
    ]
