# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_project', '0009_remove_zoomroom_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomroom',
            name='host_meeting_id',
            field=models.TextField(blank=True, null=True, verbose_name='Host Meeting ID (Zoom)'),
        ),
    ]
