# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '__first__'),
        ('zoom_project', '0010_auto_20170419_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomsettings',
            name='project',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='zoom_settings', to='project.Project',
            ),
        ),
    ]
