# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_project', '0011_zoomsettings_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomsettings',
            name='rooms',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='settings', to='zoom_project.ZoomRoom',
            ),
        ),
    ]
