# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_project', '0013_auto_20170425_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomroom',
            name='_zoom_settings',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rooms', to='zoom_project.ZoomSettings',
            ),
        ),
    ]
