# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_project', '0014_auto_20170425_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomsettings',
            name='project',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='zoom_settings', to='project.Project',
            ),
        ),
    ]
