# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-10 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from django.core.management import call_command


def create_initial_hubs(apps, schema_editor):
    call_command('create_update_hub')
    call_command('regenerate_circle_images')


class Migration(migrations.Migration):

    replaces = [('exo_hub', '0002_exohub__users'), ('exo_hub', '0003_auto_20180716_1151'), ('exo_hub',
                                                                                            '0004_auto_20180828_1132'), ('exo_hub', '0005_auto_20181123_1215'), ('exo_hub', '0006_auto_20190613_0940')]

    dependencies = [
        ('relation', '0002_hubuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exohub',
            name='_users',
            field=models.ManyToManyField(blank=True, related_name='_hubs',
                                         through='relation.HubUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=create_initial_hubs,
        ),
    ]
