# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-30 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relation', '0002_hubuser'),
        ('exo_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exohub',
            name='_users',
            field=models.ManyToManyField(blank=True, related_name='_hubs',
                                         through='relation.HubUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
