# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo_hub', '0002_exohub__users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exohub',
            name='_type',
            field=models.CharField(choices=[('C', 'Coaching'), ('T', 'Consultants'), ('A', 'Alumni')], max_length=1),
        ),
    ]
