# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-28 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo_hub', '0003_auto_20180716_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exohub',
            name='_type',
            field=models.CharField(choices=[('C', 'Coaches'), ('T', 'Consultants'), ('A', 'Alumni')], max_length=1),
        ),
    ]
