# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-23 12:15
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.management import call_command


def create_initial_hubs(apps, schema_editor):
    call_command('create_update_hub')
    call_command('regenerate_circle_images')


class Migration(migrations.Migration):

    dependencies = [
        ('exo_hub', '0004_auto_20180828_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exohub',
            name='_type',
            field=models.CharField(choices=[
                ('C', 'Coaching'), ('T', 'Consulting'),
                ('A', 'Alumni'), ('B', 'Ambassadors'),
                ('R', 'Training'), ('U', 'Building Local Ecosystem'),
                ('E', 'Entrepreneurship'), ('I', 'Investing'),
                ('O', 'Content Generation'), ('S', 'Business Development'),
                ('P', 'Speaking'), ('D', 'Advising')], max_length=1),
        ),
        migrations.RunPython(
            code=create_initial_hubs,
        ),
    ]
