# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo_hub', '0005_auto_20181123_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exohub',
            name='_type',
            field=models.CharField(choices=[('C', 'Coach'), ('T', 'Consultant'), ('A', 'Alumni'), ('B', 'Ambassador'), ('R', 'Trainer'), ('I', 'Investor')], max_length=1),
        ),
    ]
