# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import versionfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Language Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True,
                                                 verbose_name='Agreement description')),
                ('text', models.TextField(verbose_name='Agreement text')),
                (
                    'recipient', models.CharField(
                        choices=[
                            ('G', 'General'), ('C', 'Consultants'), ('U', 'Regular Users'),
                        ], default='G', max_length=1,
                    ),
                ),
                ('status', models.CharField(choices=[('A', 'Active'), ('S', 'Inactive')], default='S', max_length=1)),
                (
                    'document_name', models.CharField(
                        default='OpenExO Agreement v',
                        max_length=200, verbose_name='Agreement document name',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                (
                    'status', models.CharField(
                        choices=[
                            ('S', 'Accepted'),
                            ('P', 'Pending'), ('I', 'Revoked'),
                        ], default='P', max_length=1,
                    ),
                ),
                (
                    'agreement', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_agreements', to='agreement.Agreement',
                    ),
                ),
                (
                    'user', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='agreements', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agreement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(
                choices=[
                    ('A', 'Active'), ('I', 'Inactive'),
                    ('C', 'Cancelled'),
                ], default='I', max_length=1,
            ),
        ),
        migrations.AddField(
            model_name='agreement',
            name='version',
            field=versionfield.VersionField(),
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='text',
        ),
        migrations.AddField(
            model_name='agreement',
            name='file_name',
            field=models.CharField(default='', max_length=200, verbose_name='Agreement file name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AgreementObjectToActivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Agreement related Services',
                'verbose_name': 'Agreement related Service',
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='objects_to_activate',
            field=models.ManyToManyField(blank=True, to='agreement.AgreementObjectToActivate'),
        ),
        migrations.AlterUniqueTogether(
            name='useragreement',
            unique_together={('user', 'agreement')},
        ),
        migrations.AddField(
            model_name='agreement',
            name='domain',
            field=models.CharField(choices=[('T', 'Terms of service'), ('A', 'Activity')], default='T', max_length=1),
        ),
    ]
