# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-23 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_squashed_0011_merge_20180109_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementobjecttoactivate',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='objects_to_activate',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='domain',
            field=models.CharField(choices=[('T', 'Terms of service'), ('A', 'Activity'),
                                            ('M', 'Marketplace')], default='T', max_length=1),
        ),
        migrations.DeleteModel(
            name='AgreementObjectToActivate',
        ),
    ]
