# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-05 15:04
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_squashed_0011_merge_20180109_1532'),
    ]

    operations = []
