# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-12 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0002_auto_20190523_1026'),
        ('agreement', '0002_auto_20190705_1504'),
    ]

    operations = [
    ]
