# Generated by Django 2.2.6 on 2019-10-16 16:44

from django.db import migrations, models
from django.core.management import call_command


def update_or_create_agreements(apps, schema_editor):
    call_command('update_or_create_agreements')


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0003_merge_20190712_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='domain',
            field=models.CharField(
                choices=[
                    ('T', 'Terms of service'), ('A', 'Activity'),
                    ('M', 'Marketplace'), ('E', 'ExQ')],
                default='T', max_length=1),
        ),
        migrations.RunPython(update_or_create_agreements),
    ]
