# Generated by Django 2.2.3 on 2019-09-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_auth', '0002_usersubscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user_uuid', 'subscription')},
        ),
    ]
