# Generated by Django 2.1.3 on 2018-11-09 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields
import opportunities.manager.applicant
import opportunities.manager.opportunity
import opportunities.models.mixins.application_invitation_mixin
import opportunities.models.mixins.application_status_mixin
import opportunities.models.mixins.opportunity_applicant_mixin
import opportunities.models.mixins.opportunity_user_status_mixin
import utils.descriptors.choices_descriptor_mixin
import utils.permissions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('F', 'Draft'), ('P', 'Pending'), ('B', 'Requested'), ('J', 'Rejected'), ('T', 'Accepted'), ('D', 'Declined'), ('V', 'Removed'), ('G', 'Selected'), ('L', 'Cancelled')], default='F', max_length=1)),
                ('summary', models.TextField(blank=True, null=True)),
                ('declined_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(opportunities.models.mixins.application_status_mixin.ApplicationStatusMixin, opportunities.models.mixins.application_invitation_mixin.ApplicationInvitationMixin, utils.descriptors.choices_descriptor_mixin.ChoicesDescriptorMixin, models.Model),
            managers=[
                ('objects', opportunities.manager.applicant.ApplicantManager()),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('_status', models.CharField(choices=[('X', 'Draft'), ('R', 'Requested'), ('M', 'Removed'), ('C', 'Assigned'), ('L', 'Closed')], default='X', max_length=1)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True)),
                ('target', models.CharField(choices=[('O', 'Opened'), ('F', 'Fixed')], default='O', max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('type_project', models.CharField(choices=[('A', 'ExO Sprint'), ('B', 'ExO Sprint Support'), ('C', 'ExO Workhop'), ('D', 'ExO Talk'), ('E', 'FTI Sprint'), ('F', 'ExO on Demand'), ('G', 'ExO Advisory call'), ('H', 'Other Transformation Project')], max_length=1, verbose_name='Type of project')),
                ('client', models.CharField(max_length=200, verbose_name='Client Name')),
                ('project_status', models.CharField(choices=[('A', 'Pre-sold'), ('B', 'Sold'), ('C', 'In Execution'), ('D', 'Completed')], max_length=1)),
                ('country', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('dates', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.CharField(blank=True, max_length=200, null=True)),
                ('need_sales_assistant', models.BooleanField(default=False)),
                ('applicants', models.ManyToManyField(related_name='opportunities', through='opportunities.Applicant', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_opportunity_related', to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(to='keywords.Keyword')),
            ],
            options={
                'ordering': ['created'],
                'permissions': (('edit_opportunity', 'Edit Opportunity'), ('remove_opportunity', 'Remove Opportunity'), ('edit_admin_opportunity', 'Edit admin Opportunity'), ('assign_opportunity', 'Assign Opportunity')),
            },
            bases=(opportunities.models.mixins.opportunity_applicant_mixin.OpportunityApplicantMixin, opportunities.models.mixins.opportunity_user_status_mixin.OpportunityUserStatusMixin, utils.permissions.PermissionManagerMixin, utils.descriptors.choices_descriptor_mixin.ChoicesDescriptorMixin, models.Model),
            managers=[
                ('objects', opportunities.manager.opportunity.OpportunityManager()),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('X', 'Draft'), ('R', 'Requested'), ('M', 'Removed'), ('C', 'Assigned'), ('L', 'Closed')], default='X', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='opportunities.Opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.descriptors.choices_descriptor_mixin.ChoicesDescriptorMixin, models.Model),
        ),
        migrations.AddField(
            model_name='applicant',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants_info', to='opportunities.Opportunity'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opp_applicants_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
