# Generated by Django 2.1.3 on 2018-11-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='city',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='client',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='need_sales_assistant',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='project_status',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='type_project',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
