# Generated by Django 2.1.3 on 2018-11-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_auto_20181113_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='budget',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
