# Generated by Django 2.1.3 on 2018-11-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_applicant_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='entity',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
