# Generated by Django 2.1.3 on 2018-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_opportunity_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='budget',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='budget_currency',
            field=models.CharField(blank=True, choices=[('E', 'EURO'), ('D', 'DOLLAR'), ('C', 'CIVX')], default='D', max_length=1, null=True),
        ),
    ]
