# Generated by Django 2.1.3 on 2018-12-13 08:52

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    Opportunity = apps.get_model('opportunities', 'Opportunity')
    for opp in Opportunity.objects.all():
        opp.uuid = uuid.uuid4()
        opp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_auto_20181204_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='opportunity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True)
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='budget_currency',
            field=models.CharField(blank=True, choices=[('E', 'EUR'), ('D', 'USD'), ('C', 'CIVX')], default='D', max_length=1, null=True),
        ),
    ]
