# Generated by Django 2.2 on 2019-04-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_auto_20190425_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='mode',
            field=models.CharField(choices=[('S', 'OnSite'), ('L', 'OnLine')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
