# Generated by Django 2.2.1 on 2019-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_auto_20190429_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='num_positions',
            field=models.IntegerField(default=1),
        ),
    ]
