# Generated by Django 2.2.1 on 2019-05-14 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import utils.descriptors.choices_descriptor_mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0010_opportunity_num_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='_status',
            field=models.CharField(choices=[('X', 'Draft'), ('R', 'Requested'), ('M', 'Removed'), ('L', 'Closed')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunitystatus',
            name='status',
            field=models.CharField(choices=[('X', 'Draft'), ('R', 'Requested'), ('M', 'Removed'), ('L', 'Closed')], default='X', max_length=1),
        ),
        migrations.CreateModel(
            name='ApplicantStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('F', 'Draft'), ('P', 'Pending'), ('B', 'Requested'), ('J', 'Rejected'), ('T', 'Accepted'), ('D', 'Declined'), ('V', 'Removed'), ('G', 'Selected'), ('L', 'Cancelled')], default='B', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='opportunities.Applicant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.descriptors.choices_descriptor_mixin.ChoicesDescriptorMixin, models.Model),
        ),
    ]
