# Generated by Django 2.2.1 on 2019-05-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0012_auto_20190514_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='virtual_budget',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
