# Generated by Django 2.2.1 on 2019-05-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0012_auto_20190514_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
