# Generated by Django 2.2.1 on 2019-05-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0013_auto_20190524_1426'),
        ('opportunities', '0013_opportunity_deadline_date'),
    ]

    operations = [
    ]
