# Generated by Django 2.2.2 on 2019-06-05 15:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0015_auto_20190605_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantsow',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='applicantsow',
            name='budget_currency',
        ),
        migrations.RemoveField(
            model_name='applicantsow',
            name='virtual_budget',
        ),
        migrations.RemoveField(
            model_name='applicantsow',
            name='virtual_budget_currency',
        ),
        migrations.AddField(
            model_name='applicantsow',
            name='budgets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantsow',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sow', to='opportunities.Applicant'),
        ),
    ]
