# Generated by Django 2.2.2 on 2019-06-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0018_auto_20190612_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantsow',
            name='applicant_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicantsow',
            name='reimbursable_expenses',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='applicantsow',
            name='requester_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
