# Generated by Django 2.2.3 on 2019-07-12 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0020_auto_20190708_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('F', 'Draft'), ('P', 'Pending'), ('B', 'Requested'), ('J', 'Rejected'), ('T', 'Accepted'), ('D', 'Declined'), ('V', 'Removed'), ('G', 'Selected'), ('L', 'Cancelled'), ('A', 'Completed'), ('C', 'Feedback requester received'), ('E', 'Feedback applicant received'), ('H', 'Feedback received')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='applicantstatus',
            name='status',
            field=models.CharField(choices=[('F', 'Draft'), ('P', 'Pending'), ('B', 'Requested'), ('J', 'Rejected'), ('T', 'Accepted'), ('D', 'Declined'), ('V', 'Removed'), ('G', 'Selected'), ('L', 'Cancelled'), ('A', 'Completed'), ('C', 'Feedback requester received'), ('E', 'Feedback applicant received'), ('H', 'Feedback received')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='_status',
            field=models.CharField(choices=[('X', 'Draft'), ('R', 'Requested'), ('M', 'Removed'), ('L', 'Closed'), ('I', 'Completed')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunitystatus',
            name='status',
            field=models.CharField(choices=[('X', 'Draft'), ('R', 'Requested'), ('M', 'Removed'), ('L', 'Closed'), ('I', 'Completed')], default='X', max_length=1),
        ),
        migrations.CreateModel(
            name='ApplicantFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('explained', models.IntegerField(blank=True, null=True)),
                ('collaboration', models.IntegerField(blank=True, null=True)),
                ('communication', models.IntegerField(blank=True, null=True)),
                ('recommendation', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='opportunities.Applicant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_applicantfeedback_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
