# Generated by Django 2.2.3 on 2019-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0020_auto_20190708_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='role_code',
            field=models.CharField(
                choices=[
                    ('M', 'head_coach'),
                    ('X', 'coach'),
                    ('S', 'speaker'),
                    ('EF', 'exo_foundations'),
                    ('D', 'disruptor'),
                    ('EC', 'exo_consultant'),
                    ('TR', 'exo_trainer'),
                    ('OT', 'other')
                ],
                blank=True, null=True,
                default='OT',
                max_length=2),
        ),
        migrations.AddField(
            model_name='applicantsow',
            name='role_code',
            field=models.CharField(
                choices=[
                    ('M', 'head_coach'),
                    ('X', 'coach'),
                    ('S', 'speaker'),
                    ('EF', 'exo_foundations'),
                    ('D', 'disruptor'),
                    ('EC', 'exo_consultant'),
                    ('TR', 'exo_trainer'),
                    ('OT', 'other')
                ],
                default='OT',
                max_length=2),
        ),
    ]
