# Generated by Django 2.2.3 on 2019-09-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0021_opportunity_role_code'),
        ('opportunities', '0021_auto_20190712_0922'),
    ]

    operations = [
    ]
