# Generated by Django 2.2.5 on 2019-09-14 14:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0021_opportunity_role_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('origin', models.CharField(choices=[('T', 'Team')], max_length=1)),
                ('related_uuid', models.UUIDField()),
                ('total', models.IntegerField()),
                ('role_code', models.CharField(choices=[('M', 'head_coach'), ('X', 'coach'), ('S', 'speaker'), ('EF', 'exo_foundations'), ('D', 'disruptor'), ('EC', 'exo_consultant'), ('TR', 'exo_trainer'), ('OT', 'other')], default='OT', max_length=2)),
                ('entity', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('budgets', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunities.OpportunityGroup'),
        ),
    ]
