# Generated by Django 2.2.5 on 2019-09-14 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0022_auto_20190914_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitygroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
