# Generated by Django 2.2.5 on 2019-10-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0024_auto_20190920_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('F', 'Draft'), ('B', 'Requested'), ('J', 'Rejected'), ('V', 'Removed'), ('G', 'Selected'), ('A', 'Completed'), ('C', 'Feedback requester received'), ('E', 'Feedback applicant received'), ('H', 'Feedback received')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='applicantstatus',
            name='status',
            field=models.CharField(choices=[('F', 'Draft'), ('B', 'Requested'), ('J', 'Rejected'), ('V', 'Removed'), ('G', 'Selected'), ('A', 'Completed'), ('C', 'Feedback requester received'), ('E', 'Feedback applicant received'), ('H', 'Feedback received')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='target',
            field=models.CharField(choices=[('O', 'Opened'), ('F', 'Tagged')], default='O', max_length=1),
        ),
    ]
