# Generated by Django 2.2.6 on 2019-10-17 11:03

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0025_auto_20191015_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='duration',
            new_name='old_duration',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='due_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='applicantsow',
            name='status',
        ),
        migrations.RemoveField(
            model_name='applicantsowstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='applicantsow',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantsow',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='duration_unity',
            field=models.CharField(blank=True, choices=[('T', 'Minute'), ('H', 'Hour'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='duration_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
