# Generated by Django 2.2.6 on 2019-11-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0026_auto_20191017_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantsow',
            name='duration_unity',
            field=models.CharField(blank=True, choices=[('T', 'Minute'), ('H', 'Hour'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='applicantsow',
            name='duration_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
