# Generated by Django 2.2.6 on 2019-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0027_auto_20191102_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='mode',
            field=models.CharField(blank=True, choices=[('S', 'OnSite'), ('L', 'OnLine')], max_length=1, null=True),
        ),
    ]
