# Generated by Django 2.2.7 on 2019-11-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0028_auto_20191105_0839'),
        ('opportunities', '0023_opportunitygroup_uuid'),
    ]

    operations = [
    ]
