# Generated by Django 2.2.7 on 2019-11-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exo_role', '0001_initial'),
        ('opportunities', '0028_auto_20191105_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantsow',
            name='certification_required',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exo_role.CertificationRole'),
        ),
        migrations.AddField(
            model_name='applicantsow',
            name='exo_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exo_role.ExORole'),
        ),
        migrations.AddField(
            model_name='applicantsow',
            name='other_role_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='certification_required',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exo_role.CertificationRole'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='exo_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exo_role.ExORole'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='other_role_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
