# Generated by Django 2.2.7 on 2019-11-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0029_auto_20191112_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantsow',
            name='certification_required',
        ),
        migrations.RemoveField(
            model_name='applicantsow',
            name='exo_role',
        ),
        migrations.RemoveField(
            model_name='applicantsow',
            name='other_role_name',
        ),
    ]
