# Generated by Django 2.2.7 on 2019-11-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0029_merge_20191108_0838'),
        ('opportunities', '0030_opportunitygroup_managers'),
    ]

    operations = [
    ]
