# Generated by Django 2.2.7 on 2019-12-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0031_auto_20191119_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='context_content_object',
            field=models.CharField(blank=True, choices=[('event', 'Event'), ('project', 'Project')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='context_object_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
