# Generated by Django 2.2.7 on 2019-11-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exo_role', '0001_initial'),
        ('opportunities', '0031_merge_20191108_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitygroup',
            name='role_code',
        ),
        migrations.AddField(
            model_name='opportunitygroup',
            name='duration_unity',
            field=models.CharField(blank=True, choices=[('T', 'Minute'), ('H', 'Hour'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='opportunitygroup',
            name='duration_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunitygroup',
            name='exo_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exo_role.ExORole'),
        ),
    ]
