# Generated by Django 2.2.7 on 2019-11-27 09:02

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('opportunities', '0031_auto_20191119_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='languages',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='languages.Language'),
        ),
    ]
