# Generated by Django 2.2.7 on 2019-12-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0032_auto_20191203_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='context_content_object',
            new_name='context_content_type',
        ),
    ]
