# Generated by Django 2.2.8 on 2019-12-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0032_opportunity_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='other_category_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
