# Generated by Django 2.2.7 on 2019-11-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0033_opportunitygroup_certification_required'),
        ('opportunities', '0029_auto_20191112_1042'),
    ]

    operations = [
    ]
