# Generated by Django 2.2.7 on 2019-11-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0034_merge_20191112_1551'),
        ('opportunities', '0030_auto_20191112_1637'),
    ]

    operations = [
    ]
