# Generated by Django 2.2.7 on 2019-11-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0035_merge_20191114_1515'),
        ('opportunities', '0031_auto_20191119_0934'),
    ]

    operations = [
    ]
