# Generated by Django 2.2.7 on 2019-12-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0036_merge_20191126_1631'),
        ('opportunities', '0032_opportunity_languages'),
    ]

    operations = [
    ]
