# Generated by Django 2.2.8 on 2019-12-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0033_opportunity_other_category_name'),
        ('opportunities', '0037_merge_20191205_1210'),
    ]

    operations = [
    ]
