# Generated by Django 2.2.7 on 2019-12-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0033_auto_20191203_1613'),
        ('opportunities', '0038_merge_20191211_1447'),
    ]

    operations = [
    ]
