# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-09 06:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0046_auto_20190710_0710'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('team', '0005_auto_20190424_0858'),
        ('team', '0001_squashed_0010_auto_20170710_0717'),
        ('project', '0003_squashed_0044_auto_20170710_0717'),
        ('team', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name_plural': 'Assignment Advice',
                'verbose_name': 'Assignment Advices',
            },
        ),
        migrations.CreateModel(
            name='AssignmentAdviceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('assignment_advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                        related_name='assignment_advice_items', to='assignment.AssignmentAdvice')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='assignment_assignmentadviceitem_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assignment Advice Items',
                'verbose_name': 'Assignment Advices Item',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name_plural': 'Assignment Resource',
                'verbose_name': 'Assignment Resources',
            },
        ),
        migrations.CreateModel(
            name='AssignmentResourceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('link', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('assignment_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                          related_name='assignment_resource_items', to='assignment.AssignmentResource')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='assignment_assignmentresourceitem_related', to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(blank=True, null=True)),
                ('iframe', models.TextField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('A', 'Available'),
                                                     ('U', 'Unavailable')], default='A', max_length=1)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('P', 'PDF'), ('D', 'Document'), ('S', 'Slides'), ('F', 'Form'), (
                    'R', 'Spreedshet'), ('V', 'Video'), ('L', 'Link'), ('U', 'Uploader')], default='P', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Assignment Resource Items',
                'verbose_name': 'Assignment Resource Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('streams', multiselectfield.db.fields.MultiSelectField(choices=[
                 ('S', 'Edge Stream'), ('T', 'Core Stream')], default='S', max_length=3, verbose_name='Streams')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='assignment_assignmentstep_related', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='assignments_step', to='project.Step')),
            ],
            options={
                'verbose_name_plural': 'Assignment Step',
                'verbose_name': 'Assignment Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentStepTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('assignment_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='assignment_step_teams', to='assignment.AssignmentStep')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='assignment_assignmentstepteam_related', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='assignment_step_teams', to='team.Team')),
            ],
            options={
                'verbose_name_plural': 'Assignment Steps Team',
                'verbose_name': 'Assignment Step Team',
            },
        ),
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name_plural': 'Assignment Tasks',
                'verbose_name': 'Assignment Task',
            },
        ),
        migrations.CreateModel(
            name='AssignmentTaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assignment_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='assignment_task_items', to='assignment.AssignmentTask')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='assignment_assignmenttaskitem_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assignment Task Items',
                'verbose_name': 'Assignment Task Item',
            },
        ),
        migrations.CreateModel(
            name='AssignmentTaskTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('T', 'To Do'), ('D', 'Done')], default='T', max_length=1)),
                ('assignment_step_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                           related_name='assignment_tasks_team', to='assignment.AssignmentStepTeam')),
                ('assignment_task_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                           related_name='assignment_tasks_team', to='assignment.AssignmentTaskItem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='assignment_assignmenttaskteam_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assignment Tasks Team',
                'verbose_name': 'Assignment Task Team',
            },
        ),
        migrations.CreateModel(
            name='AssignmentText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Assignments Text',
                'verbose_name': 'Assignment Text',
            },
        ),
        migrations.CreateModel(
            name='InformationBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=400, null=True)),
                ('type', models.CharField(choices=[('T', 'Task'), ('E', 'Text'),
                                                   ('R', 'Resource'), ('A', 'Advice')], default='T', max_length=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='assignment_informationblock_related', to=settings.AUTH_USER_MODEL)),
                ('section', models.CharField(choices=[('L', 'Learn'), ('D', 'Deliver')], default='L', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Information Block',
                'verbose_name': 'Information Blocks',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='assignmenttext',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='assignments_text', to='assignment.InformationBlock'),
        ),
        migrations.AddField(
            model_name='assignmenttext',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='assignment_assignmenttext_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='assignment_tasks', to='assignment.InformationBlock'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='assignment_assignmenttask_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentresource',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='assignment_resources', to='assignment.InformationBlock'),
        ),
        migrations.AddField(
            model_name='assignmentresource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='assignment_assignmentresource_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentadvice',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='assignment_advices', to='assignment.InformationBlock'),
        ),
        migrations.AddField(
            model_name='assignmentadvice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='assignment_assignmentadvice_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentstep',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='assignmenttaskitem',
            name='name',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterModelOptions(
            name='assignmentstep',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='assignmentstepteam',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentstepteam',
            unique_together={('assignment_step', 'team')},
        ),
        migrations.AlterModelOptions(
            name='assignmentadvice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assignmentresource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assignmenttaskitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assignmenttext',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assignmenttask',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='assignmenttaskteam',
            unique_together={('assignment_step_team', 'assignment_task_item')},
        ),
    ]
