# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_squashed_0010_auto_20190522_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentadviceitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='assignmentresourceitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='assignmenttaskteam',
            options={},
        ),
        migrations.AlterModelOptions(
            name='informationblock',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='assignmentresourceitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
