# Generated by Django 2.2.4 on 2019-08-26 14:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20190710_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentstep',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='informationblock',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'assignment'), ('model', 'AssignmentStep')), models.Q(
                ('app_label', 'assignment'), ('model', 'AssignmentTaskItem')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
