# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-09 06:22
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import exo_accounts.manager.user
import model_utils.fields
import timezone_field.fields
import utils.images.fields
import utils.mixins.location_timezone_mixin
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short name')),
                ('profile_picture', utils.images.fields.PowerImageField(backgrounds=('#4DB6AC', '#5E97F6', '#90A4AE', '#A1887F', '#AED581', '#B39DDB', '#C5CD57', '#E897F6', '#F87165', '#EA80FC'),
                                                                        blank=True, null=True, thumbnails=((32, 32), (56, 56), (150, 150), (24, 24), (48, 48), (96, 96), (144, 144)), upload_to='avatars', verbose_name='profile picture')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False,
                                                       null=True, populate_from='get_full_name', unique=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                                            related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('short_me', models.TextField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bio_me', models.TextField(blank=True, null=True)),
                ('password_updated', models.BooleanField(default=False)),
                ('user_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='User title')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('_platform_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), (
                    'pt', 'Portuguese'), ('ja', 'Japanese'), ('zh-hans', 'Simplified Chinese')], default='en', max_length=8)),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('_username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('profile_picture_origin', models.CharField(choices=[
                 ('D', 'Image default'), ('L', 'Image linkedin'), ('U', 'Image from user')], default='D', max_length=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
            ],
            options={
                'abstract': False,
                'db_table': 'accounts_user',
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('verif_key', models.CharField(max_length=40)),
                ('verified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_host', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_email', models.CharField(choices=[
                 ('P', 'Personal'), ('E', 'ExO Email')], default='P', max_length=1)),
            ],
            options={
                'abstract': False,
                'db_table': 'accounts_emailaddress'
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('user_edit_profile', 'Edit User Profile'),),
                     'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', exo_accounts.manager.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('network_type', models.CharField(choices=[
                 ('S', 'Skype'), ('L', 'Linkedin'), ('T', 'Twitter'), ('M', 'Medium'), ('P', 'Website'), ('F', 'Facebook')], max_length=1)),
                ('value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='social_networks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'SocialNetwork',
                'verbose_name_plural': 'SocialNetworks',
                'db_table': 'accounts_socialnetworks',
            },
        ),
    ]
