# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-10 07:10
from __future__ import unicode_literals

from django.db import migrations
import utils.mixins.location_timezone_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('exo_accounts', '0001_squashed_0013_auto_20190524_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=utils.mixins.location_timezone_mixin.TimeZoneField(blank=True, null=True),
        ),
    ]
