# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-17 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_accounts', '0014_auto_20190604_1044'),
        ('exo_accounts', '0002_auto_20190710_0710'),
    ]

    operations = [
    ]
