# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-02 11:37
from __future__ import unicode_literals

from django.db import migrations
import utils.images.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exo_accounts', '0014_auto_20190604_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=utils.images.fields.PowerImageField(backgrounds=('#4DB6AC', '#5E97F6', '#90A4AE', '#A1887F', '#AED581', '#B39DDB', '#C5CD57', '#E897F6', '#F87165', '#EA80FC'), blank=True, null=True, thumbnails=((24, 24), (48, 48), (96, 96), (144, 144)), upload_to='avatars', verbose_name='profile picture'),
        ),
    ]
