# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-05 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_accounts', '0015_merge_20190717_2101'),
        ('exo_accounts', '0015_auto_20190802_1137'),
    ]

    operations = [
    ]
