# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-18 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_accounts', '0016_merge_20190805_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('user_edit_profile', 'Edit User Profile'), ('view_marketplace_full', 'Can view Marketplace'), (
                'exq_access', 'Access to ExQ Tool')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
