# Generated by Django 2.2.6 on 2019-10-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo_accounts', '0018_auto_20190827_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('user_edit_profile', 'Edit User Profile'), ('view_marketplace_full', 'Can view Marketplace'), ('view_exq_full', 'Can view ExQ'), ('exq_access', 'Access to ExQ Tool')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
