# Generated by Django 2.2.7 on 2019-11-25 10:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exo_role', '0001_initial'),
        ('project', '0069_auto_20190826_1448'),
        ('team', '0008_team_uuid_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityTeamGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('group_uuid', models.UUIDField(blank=True, null=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_group', to='team.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvisorRequestSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total', models.IntegerField()),
                ('entity', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('duration_unity', models.CharField(blank=True, choices=[('T', 'Minute'), ('H', 'Hour'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month')], max_length=1, null=True)),
                ('duration_value', models.IntegerField(blank=True, null=True)),
                ('budgets', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('certification_required', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exo_role.CertificationRole')),
                ('exo_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exo_role.ExORole')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_request_settings', to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
