# Generated by Django 2.1.5 on 2019-01-31 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('_hash_code', models.CharField(blank=True, max_length=256, null=True)),
                ('_stripe_auth_token_code', models.CharField(blank=True, max_length=256, null=True)),
                ('_stripe_payment_id', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD')], default='eur', max_length=4)),
                ('concept', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('X', 'Error'), ('C', 'Canceled'), ('E', 'Removed'), ('A', 'Paid'), ('V', 'Verified')], default='P', max_length=1)),
                ('date_payment', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_payment_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
