# Generated by Django 2.1.5 on 2019-02-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='url_notification',
            field=models.URLField(blank=True, null=True),
        ),
    ]
