# Generated by Django 2.2.1 on 2019-06-06 16:23

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190604_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=payments.models.payment.directory_path, validators=[payments.models.payment.validate_pdf_file]),
        ),
        migrations.AddField(
            model_name='payment',
            name='email_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='email_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
