# Generated by Django 2.2.1 on 2019-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190606_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='intent_client_secret_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='intent_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
