# Generated by Django 2.2.2 on 2019-08-07 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20190611_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='_type',
            field=models.CharField(blank=True, choices=[('C', 'Certification')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('S', 'Synchronizing'), ('P', 'Pending'), ('X', 'Error'), ('C', 'Canceled'), ('E', 'Removed'), ('A', 'Paid'), ('V', 'Verified')], default='P', max_length=1),
        ),
    ]
