# Generated by Django 2.2.4 on 2019-08-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20190807_0644'),
        ('payments', '0007_auto_20190806_1423'),
    ]

    operations = [
    ]
