# Generated by Django 2.2.4 on 2019-08-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_merge_20190807_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='send_by_email',
            field=models.BooleanField(default=True),
        ),
    ]
