# Generated by Django 2.2.5 on 2019-09-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_generate_and_send_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='generate_and_send_invoice',
            new_name='send_invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_eur',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_vat',
        ),
        migrations.AlterField(
            model_name='payment',
            name='vat',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
