# Generated by Django 2.2.6 on 2019-10-22 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import multiselectfield.db.fields
import team.models.mixins.team_permissions
import utils.permissions.base_mixin
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('level', multiselectfield.db.fields.MultiSelectField(choices=[('admin', 'Admin'), ('basic', 'Basic'), ('readonly', 'Readonly'), ('notification', 'Notification')], default='basic', max_length=20)),
                ('default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_projectteamrole_related', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_roles', to='project.Project')),
            ],
            options={
                'ordering': ['level', 'role'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_team_related', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='project.Project')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='utils.Stream')),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('admin', 'Admin'), ('basic', 'Basic'), ('readonly', 'Readonly'), ('notification', 'Notification')),
            },
            bases=(utils.permissions.base_mixin.PermissionManagerMixin, team.models.mixins.team_permissions.TeamPermissions, models.Model),
        ),
        migrations.CreateModel(
            name='TeamStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='project.Step')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='team.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTeamRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_userteamrole_related', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_roles', to='team.Team')),
                ('team_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_roles', to='team.ProjectTeamRole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team_role__role'],
                'unique_together': {('user', 'team', 'team_role')},
            },
        ),
    ]
