# Generated by Django 2.2.2 on 2019-07-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = []
