# Generated by Django 2.2.3 on 2019-07-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190701_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='survey.SurveyFilled'),
        ),
        migrations.AlterField(
            model_name='surveyfilled',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
