# Generated by Django 2.2.3 on 2019-08-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_populate_industries'),
        ('survey', '0003_auto_20190703_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='cohort',
        ),
        migrations.AddField(
            model_name='surveyfilled',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='industry.Industry'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Cohort',
        ),
    ]
