# Generated by Django 2.2.4 on 2019-08-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190803_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('M', 'Massive Transformative Purpose'), ('S', 'Staff on-demand'), ('C', 'Community & Crowd'), ('A', 'Algorithms and Data'), ('L', 'Leveraged Assets'),
                                            ('E', 'Engagement'), ('I', 'Interfaces'), ('D', 'Dashboards'), ('X', 'Experimentation'), ('F', 'Autonomy'), ('O', 'Social'), ('B', 'Business Type Model')], max_length=1),
        ),
        migrations.AlterField(
            model_name='result',
            name='section',
            field=models.CharField(choices=[('M', 'Massive Transformative Purpose'), ('S', 'Staff on-demand'), ('C', 'Community & Crowd'), ('A', 'Algorithms and Data'), ('L', 'Leveraged Assets'),
                                            ('E', 'Engagement'), ('I', 'Interfaces'), ('D', 'Dashboards'), ('X', 'Experimentation'), ('F', 'Autonomy'), ('O', 'Social'), ('B', 'Business Type Model')], max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyfilled',
            name='organization',
            field=models.CharField(default='', max_length=500),
        ),
    ]
