# Generated by Django 2.2.4 on 2019-09-11 09:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_answer_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score', models.FloatField()),
                ('survey_filled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_logs', to='survey.SurveyFilled')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
