# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExOArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created', model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created',
                    ),
                ),
                (
                    'modified', model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified',
                    ),
                ),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                (
                    'code', models.CharField(
                        choices=[
                            ('O', 'organization'),
                            ('I', 'institution'), ('P', 'people'),
                        ], max_length=150,
                    ),
                ),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'ExOAreas',
                'verbose_name': 'ExOArea',
                'ordering': ['order'],
            },
        ),
    ]
