# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 18:07
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


def create_exo_areas(apps, schema_editor):
    ExOArea = apps.get_model('exo_area', 'ExOArea')
    order = 1
    for code, name in settings.EXO_AREA_CH_EXO_AREAS_NAMES:
        area, _ = ExOArea.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'order': order,
            },
        )
        order += 1


class Migration(migrations.Migration):

    dependencies = [
        ('exo_area', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_exo_areas),
    ]
