# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'ExO WorkShop', 'verbose_name_plural': 'ExO WorkShops'},
        ),
    ]
