# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180821_1204'),
        ('workshop', '0002_auto_20180613_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'ExO Certification Workshop',
                     'verbose_name_plural': 'ExO Certification Workshops'},
        ),
        migrations.AddField(
            model_name='workshop',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='currency',
            field=models.CharField(choices=[('E', '€'), ('D', '$')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='follow_type',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('P', 'In Person'), ('S', 'Streaming'), ('V', 'Virtual')], default='P', max_length=5),
        ),
        migrations.AddField(
            model_name='workshop',
            name='languages',
            field=models.ManyToManyField(to='core.Language'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='sub_title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='type_event',
            field=models.CharField(choices=[('T', 'ExO Talk'), ('B', 'ExO Book launch'),
                                            ('W', 'ExO Workshop')], default='W', max_length=1),
        ),
    ]
