# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20190118_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='follow_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'On Site'), ('S', 'Streaming'), ('V', 'Virtual')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='type_event',
            field=models.CharField(choices=[('T', 'ExO Talk'), ('B', 'ExO Book launch'), ('W', 'ExO Workshop'), ('S', 'ExO Summit')], default='W', max_length=1),
        ),
    ]
