# Generated by Django 2.2.7 on 2019-11-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20190613_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='follow_type',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='type_event',
        ),
    ]
